export const CATEGORIES = [
  { slug: "hospitals", name: "Hospitals & Medical Centers", icon: "Building2", sortOrder: 1 },
  { slug: "clinics", name: "General Clinics & Polyclinics", icon: "Stethoscope", sortOrder: 2 },
  { slug: "dental", name: "Dental Clinics", icon: "Smile", sortOrder: 3 },
  { slug: "dermatology", name: "Dermatology & Skin Care", icon: "Sparkles", sortOrder: 4 },
  { slug: "ophthalmology", name: "Eye Care & Ophthalmology", icon: "Eye", sortOrder: 5 },
  { slug: "cardiology", name: "Cardiology & Heart Care", icon: "HeartPulse", sortOrder: 6 },
  { slug: "orthopedics", name: "Orthopedics & Sports Medicine", icon: "Bone", sortOrder: 7 },
  { slug: "mental-health", name: "Mental Health & Psychology", icon: "Brain", sortOrder: 8 },
  { slug: "pediatrics", name: "Pediatrics & Child Health", icon: "Baby", sortOrder: 9 },
  { slug: "ob-gyn", name: "OB/GYN & Women's Health", icon: "Heart", sortOrder: 10 },
  { slug: "ent", name: "ENT (Ear, Nose & Throat)", icon: "Ear", sortOrder: 11 },
  { slug: "fertility-ivf", name: "Fertility & IVF", icon: "Flower2", sortOrder: 12 },
  { slug: "physiotherapy", name: "Physiotherapy & Rehabilitation", icon: "Activity", sortOrder: 13 },
  { slug: "nutrition-dietetics", name: "Nutrition & Dietetics", icon: "Apple", sortOrder: 14 },
  { slug: "pharmacy", name: "Pharmacies", icon: "Pill", sortOrder: 15 },
  { slug: "labs-diagnostics", name: "Labs & Diagnostics", icon: "FlaskConical", sortOrder: 16 },
  { slug: "radiology-imaging", name: "Radiology & Imaging", icon: "ScanLine", sortOrder: 17 },
  { slug: "home-healthcare", name: "Home Healthcare", icon: "Home", sortOrder: 18 },
  { slug: "alternative-medicine", name: "Alternative & Holistic Medicine", icon: "Leaf", sortOrder: 19 },
  { slug: "cosmetic-plastic", name: "Cosmetic & Plastic Surgery", icon: "Scissors", sortOrder: 20 },
  { slug: "neurology", name: "Neurology & Brain Health", icon: "Zap", sortOrder: 21 },
  { slug: "urology", name: "Urology", icon: "Droplets", sortOrder: 22 },
  { slug: "gastroenterology", name: "Gastroenterology & Digestive", icon: "CircleDot", sortOrder: 23 },
  { slug: "oncology", name: "Oncology & Cancer Care", icon: "Shield", sortOrder: 24 },
  { slug: "emergency-care", name: "Emergency & Urgent Care", icon: "Siren", sortOrder: 25 },
  { slug: "wellness-spas", name: "Wellness Centers & Medical Spas", icon: "Waves", sortOrder: 26 },
] as const;

export const SUBCATEGORIES: Record<string, { slug: string; name: string; sortOrder: number }[]> = {
  hospitals: [
    { slug: "government-hospitals", name: "Government Hospitals", sortOrder: 1 },
    { slug: "private-hospitals", name: "Private Hospitals", sortOrder: 2 },
    { slug: "university-hospitals", name: "University Hospitals", sortOrder: 3 },
    { slug: "specialty-hospitals", name: "Specialty Hospitals", sortOrder: 4 },
    { slug: "day-surgery-centers", name: "Day Surgery Centers", sortOrder: 5 },
  ],
  clinics: [
    { slug: "general-practice", name: "General Practice", sortOrder: 1 },
    { slug: "multi-specialty-clinics", name: "Multi-Specialty Clinics", sortOrder: 2 },
    { slug: "family-medicine", name: "Family Medicine", sortOrder: 3 },
    { slug: "walk-in-clinics", name: "Walk-In Clinics", sortOrder: 4 },
  ],
  dental: [
    { slug: "general-dentistry", name: "General Dentistry", sortOrder: 1 },
    { slug: "orthodontics", name: "Orthodontics", sortOrder: 2 },
    { slug: "cosmetic-dentistry", name: "Cosmetic Dentistry", sortOrder: 3 },
    { slug: "pediatric-dentistry", name: "Pediatric Dentistry", sortOrder: 4 },
    { slug: "oral-surgery", name: "Oral Surgery", sortOrder: 5 },
    { slug: "implants", name: "Dental Implants", sortOrder: 6 },
    { slug: "endodontics", name: "Endodontics", sortOrder: 7 },
    { slug: "periodontics", name: "Periodontics", sortOrder: 8 },
  ],
  dermatology: [
    { slug: "medical-dermatology", name: "Medical Dermatology", sortOrder: 1 },
    { slug: "cosmetic-dermatology", name: "Cosmetic Dermatology", sortOrder: 2 },
    { slug: "laser-treatments", name: "Laser Treatments", sortOrder: 3 },
    { slug: "hair-restoration", name: "Hair Restoration", sortOrder: 4 },
  ],
  ophthalmology: [
    { slug: "lasik-refractive", name: "LASIK & Refractive Surgery", sortOrder: 1 },
    { slug: "retina-specialists", name: "Retina Specialists", sortOrder: 2 },
    { slug: "pediatric-ophthalmology", name: "Pediatric Ophthalmology", sortOrder: 3 },
    { slug: "glaucoma-specialists", name: "Glaucoma Specialists", sortOrder: 4 },
    { slug: "optical-shops", name: "Optical Shops", sortOrder: 5 },
  ],
  "mental-health": [
    { slug: "psychiatry", name: "Psychiatry", sortOrder: 1 },
    { slug: "clinical-psychology", name: "Clinical Psychology", sortOrder: 2 },
    { slug: "counseling", name: "Counseling & Therapy", sortOrder: 3 },
    { slug: "child-psychology", name: "Child & Adolescent Psychology", sortOrder: 4 },
    { slug: "addiction-treatment", name: "Addiction Treatment", sortOrder: 5 },
  ],
  "fertility-ivf": [
    { slug: "ivf-centers", name: "IVF Centers", sortOrder: 1 },
    { slug: "egg-freezing", name: "Egg Freezing", sortOrder: 2 },
    { slug: "male-fertility", name: "Male Fertility", sortOrder: 3 },
    { slug: "genetic-testing", name: "Genetic Testing", sortOrder: 4 },
  ],
  "alternative-medicine": [
    { slug: "acupuncture", name: "Acupuncture", sortOrder: 1 },
    { slug: "homeopathy", name: "Homeopathy", sortOrder: 2 },
    { slug: "ayurveda", name: "Ayurveda", sortOrder: 3 },
    { slug: "traditional-chinese-medicine", name: "Traditional Chinese Medicine", sortOrder: 4 },
    { slug: "chiropractic", name: "Chiropractic", sortOrder: 5 },
    { slug: "naturopathy", name: "Naturopathy", sortOrder: 6 },
    { slug: "hijama-cupping", name: "Hijama & Cupping Therapy", sortOrder: 7 },
  ],
  "home-healthcare": [
    { slug: "nursing-care", name: "Nursing Care", sortOrder: 1 },
    { slug: "physiotherapy-at-home", name: "Physiotherapy at Home", sortOrder: 2 },
    { slug: "elderly-care", name: "Elderly Care", sortOrder: 3 },
    { slug: "post-surgery-care", name: "Post-Surgery Care", sortOrder: 4 },
    { slug: "iv-drip-therapy", name: "IV Drip Therapy", sortOrder: 5 },
    { slug: "lab-sample-collection", name: "Lab Sample Collection", sortOrder: 6 },
  ],
  "cosmetic-plastic": [
    { slug: "rhinoplasty", name: "Rhinoplasty", sortOrder: 1 },
    { slug: "liposuction", name: "Liposuction", sortOrder: 2 },
    { slug: "breast-surgery", name: "Breast Surgery", sortOrder: 3 },
    { slug: "facelift", name: "Facelift & Rejuvenation", sortOrder: 4 },
    { slug: "botox-fillers", name: "Botox & Fillers", sortOrder: 5 },
  ],
};
