// ─── UAE Cities ───────────────────────────────────────────────────────────────

export const CITIES = [
  {
    slug: "dubai",
    name: "Dubai",
    emirate: "Dubai",
    country: "ae",
    nameAr: "دبي",
    latitude: "25.2048493",
    longitude: "55.2707828",
    sortOrder: 1,
    description: "Dubai is the most populous city in the UAE, home to world-class hospitals, specialty clinics, and healthcare free zones including Dubai Healthcare City (DHCC).",
  },
  {
    slug: "abu-dhabi",
    name: "Abu Dhabi",
    emirate: "Abu Dhabi",
    country: "ae",
    nameAr: "أبوظبي",
    latitude: "24.4538352",
    longitude: "54.3773438",
    sortOrder: 2,
    description: "Abu Dhabi, the capital of the UAE, offers premier healthcare services regulated by the Department of Health (DOH), with major facilities on Al Reem Island, Al Maryah Island, and Khalifa City.",
  },
  {
    slug: "sharjah",
    name: "Sharjah",
    emirate: "Sharjah",
    country: "ae",
    nameAr: "الشارقة",
    latitude: "25.3462900",
    longitude: "55.4209000",
    sortOrder: 3,
    description: "Sharjah is the third-largest emirate, with a growing healthcare sector offering affordable clinics and hospitals across Al Nahda, Al Majaz, and Al Taawun.",
  },
  {
    slug: "ajman",
    name: "Ajman",
    emirate: "Ajman",
    country: "ae",
    nameAr: "عجمان",
    latitude: "25.4052165",
    longitude: "55.5136433",
    sortOrder: 4,
    description: "Ajman offers accessible healthcare services with clinics and hospitals serving the emirate's growing population.",
  },
  {
    slug: "ras-al-khaimah",
    name: "Ras Al Khaimah",
    emirate: "Ras Al Khaimah",
    country: "ae",
    nameAr: "رأس الخيمة",
    latitude: "25.7895300",
    longitude: "55.9432000",
    sortOrder: 5,
    description: "Ras Al Khaimah features a mix of government and private healthcare facilities, with growing medical tourism especially in wellness and rehabilitation.",
  },
  {
    slug: "fujairah",
    name: "Fujairah",
    emirate: "Fujairah",
    country: "ae",
    nameAr: "الفجيرة",
    latitude: "25.1288500",
    longitude: "56.3264600",
    sortOrder: 6,
    description: "Fujairah, on the eastern coast of the UAE, provides essential healthcare services through its government hospital and private clinics.",
  },
  {
    slug: "umm-al-quwain",
    name: "Umm Al Quwain",
    emirate: "Umm Al Quwain",
    country: "ae",
    nameAr: "أم القيوين",
    latitude: "25.5647200",
    longitude: "55.5553200",
    sortOrder: 7,
    description: "Umm Al Quwain is the least populated emirate, with healthcare services centered around the main city area.",
  },
  {
    slug: "al-ain",
    name: "Al Ain",
    emirate: "Abu Dhabi",
    country: "ae",
    nameAr: "العين",
    latitude: "24.1917200",
    longitude: "55.7606400",
    sortOrder: 8,
    description: "Al Ain, the Garden City of the UAE, is home to Tawam Hospital and several private healthcare facilities serving the inland region.",
  },

  // ─── Qatar Cities ─────────────────────────────────────────────────────────────

  {
    slug: "doha",
    name: "Doha",
    emirate: "Doha",
    country: "qa",
    nameAr: "الدوحة",
    latitude: "25.2854500",
    longitude: "51.5310400",
    sortOrder: 1,
    description: "Doha is the capital of Qatar and home to Hamad Medical Corporation, Sidra Medicine, and a rapidly expanding private healthcare sector.",
  },
  {
    slug: "al-wakrah",
    name: "Al Wakrah",
    emirate: "Al Wakrah",
    country: "qa",
    nameAr: "الوكرة",
    latitude: "25.1659200",
    longitude: "51.5979200",
    sortOrder: 2,
    description: "Al Wakrah is Qatar's second-largest city, with growing healthcare infrastructure including Al Wakra Hospital.",
  },
  {
    slug: "al-khor",
    name: "Al Khor",
    emirate: "Al Khor",
    country: "qa",
    nameAr: "الخور",
    latitude: "25.6804400",
    longitude: "51.4968500",
    sortOrder: 3,
    description: "Al Khor is a northern Qatar city with healthcare services centered around Al Khor Hospital and local clinics.",
  },
  {
    slug: "al-rayyan",
    name: "Al Rayyan",
    emirate: "Al Rayyan",
    country: "qa",
    nameAr: "الريان",
    latitude: "25.2919300",
    longitude: "51.4244200",
    sortOrder: 4,
    description: "Al Rayyan is one of Qatar's largest municipalities, with numerous clinics and healthcare centers serving its residential communities.",
  },
  {
    slug: "umm-salal",
    name: "Umm Salal",
    emirate: "Umm Salal",
    country: "qa",
    nameAr: "أم صلال",
    latitude: "25.4084600",
    longitude: "51.3973300",
    sortOrder: 5,
    description: "Umm Salal is a growing municipality north of Doha with expanding healthcare services.",
  },
  {
    slug: "lusail",
    name: "Lusail",
    emirate: "Lusail",
    country: "qa",
    nameAr: "لوسيل",
    latitude: "25.4300000",
    longitude: "51.4900000",
    sortOrder: 6,
    description: "Lusail is Qatar's newest planned city with state-of-the-art healthcare facilities being developed as part of its master plan.",
  },

  // ─── Saudi Arabia Cities ──────────────────────────────────────────────────────

  {
    slug: "riyadh",
    name: "Riyadh",
    emirate: "Riyadh Region",
    country: "sa",
    nameAr: "الرياض",
    latitude: "24.7135500",
    longitude: "46.6752900",
    sortOrder: 1,
    description: "Riyadh is the capital of Saudi Arabia and the largest healthcare market in the GCC, home to King Faisal Specialist Hospital, KFMC, and hundreds of private hospitals.",
  },
  {
    slug: "jeddah",
    name: "Jeddah",
    emirate: "Makkah Region",
    country: "sa",
    nameAr: "جدة",
    latitude: "21.4858000",
    longitude: "39.1925000",
    sortOrder: 2,
    description: "Jeddah is Saudi Arabia's commercial capital and Red Sea gateway, with major hospitals including King Abdulaziz University Hospital and Saudi German Hospital.",
  },
  {
    slug: "mecca",
    name: "Mecca",
    emirate: "Makkah Region",
    country: "sa",
    nameAr: "مكة المكرمة",
    latitude: "21.3891000",
    longitude: "39.8579000",
    sortOrder: 3,
    description: "Mecca is the holiest city in Islam with healthcare infrastructure designed to serve millions of pilgrims annually, including multiple MOH hospitals.",
  },
  {
    slug: "medina",
    name: "Medina",
    emirate: "Madinah Region",
    country: "sa",
    nameAr: "المدينة المنورة",
    latitude: "24.4686800",
    longitude: "39.6142000",
    sortOrder: 4,
    description: "Medina is home to major healthcare facilities serving residents and pilgrims, including King Fahad Hospital and Madinah General Hospital.",
  },
  {
    slug: "dammam",
    name: "Dammam",
    emirate: "Eastern Province",
    country: "sa",
    nameAr: "الدمام",
    latitude: "26.3927000",
    longitude: "49.9777000",
    sortOrder: 5,
    description: "Dammam is the capital of the Eastern Province and a hub for healthcare in eastern Saudi Arabia, with facilities including Dammam Medical Complex.",
  },
  {
    slug: "khobar",
    name: "Khobar",
    emirate: "Eastern Province",
    country: "sa",
    nameAr: "الخبر",
    latitude: "26.2172000",
    longitude: "50.1971000",
    sortOrder: 6,
    description: "Khobar is a major commercial city in the Eastern Province with a concentration of private healthcare facilities and specialist clinics.",
  },
  {
    slug: "dhahran",
    name: "Dhahran",
    emirate: "Eastern Province",
    country: "sa",
    nameAr: "الظهران",
    latitude: "26.2361000",
    longitude: "50.0393000",
    sortOrder: 7,
    description: "Dhahran is home to Saudi Aramco's healthcare facilities and Johns Hopkins Aramco Healthcare, one of the region's most advanced medical centers.",
  },
  {
    slug: "tabuk",
    name: "Tabuk",
    emirate: "Tabuk Region",
    country: "sa",
    nameAr: "تبوك",
    latitude: "28.3838000",
    longitude: "36.5550000",
    sortOrder: 8,
    description: "Tabuk is the largest city in northwestern Saudi Arabia with healthcare services centered around King Fahad Specialist Hospital and private clinics.",
  },
  {
    slug: "abha",
    name: "Abha",
    emirate: "Asir Region",
    country: "sa",
    nameAr: "أبها",
    latitude: "18.2164000",
    longitude: "42.5053000",
    sortOrder: 9,
    description: "Abha is the capital of the Asir region in southwestern Saudi Arabia, with healthcare facilities including Asir Central Hospital.",
  },
  {
    slug: "taif",
    name: "Taif",
    emirate: "Makkah Region",
    country: "sa",
    nameAr: "الطائف",
    latitude: "21.2703000",
    longitude: "40.4158000",
    sortOrder: 10,
    description: "Taif is a major city in the Makkah Region with a growing healthcare sector including King Faisal Hospital and several private facilities.",
  },
  {
    slug: "buraidah",
    name: "Buraidah",
    emirate: "Qassim Region",
    country: "sa",
    nameAr: "بريدة",
    latitude: "26.3260000",
    longitude: "43.9750000",
    sortOrder: 11,
    description: "Buraidah is the capital of the Qassim Region with healthcare services including Qassim Central Hospital and Buraidah Central Hospital.",
  },
  {
    slug: "hail",
    name: "Hail",
    emirate: "Hail Region",
    country: "sa",
    nameAr: "حائل",
    latitude: "27.5114000",
    longitude: "41.7208000",
    sortOrder: 12,
    description: "Hail is a northern Saudi Arabian city with healthcare infrastructure including King Khalid Hospital and private medical centers.",
  },
  {
    slug: "jazan",
    name: "Jazan",
    emirate: "Jazan Region",
    country: "sa",
    nameAr: "جازان",
    latitude: "16.8892000",
    longitude: "42.5700000",
    sortOrder: 13,
    description: "Jazan is a southwestern coastal city with healthcare services including Jazan General Hospital and growing private sector capacity.",
  },
  {
    slug: "najran",
    name: "Najran",
    emirate: "Najran Region",
    country: "sa",
    nameAr: "نجران",
    latitude: "17.4933000",
    longitude: "44.1277000",
    sortOrder: 14,
    description: "Najran is a southern Saudi city near the Yemen border, with healthcare centered around Najran General Hospital and King Khalid Hospital.",
  },
  {
    slug: "al-ahsa",
    name: "Al Ahsa",
    emirate: "Eastern Province",
    country: "sa",
    nameAr: "الأحساء",
    latitude: "25.3797000",
    longitude: "49.5866000",
    sortOrder: 15,
    description: "Al Ahsa is the largest oasis in the world and a growing healthcare market in eastern Saudi Arabia, with King Fahad Hospital and multiple private facilities.",
  },

  // ─── Bahrain Cities ───────────────────────────────────────────────────────────

  {
    slug: "manama",
    name: "Manama",
    emirate: "Capital Governorate",
    country: "bh",
    nameAr: "المنامة",
    latitude: "26.2235000",
    longitude: "50.5876000",
    sortOrder: 1,
    description: "Manama is the capital of Bahrain and its healthcare hub, home to Salmaniya Medical Complex, King Hamad University Hospital, and numerous private hospitals.",
  },
  {
    slug: "muharraq",
    name: "Muharraq",
    emirate: "Muharraq Governorate",
    country: "bh",
    nameAr: "المحرق",
    latitude: "26.2572000",
    longitude: "50.6119000",
    sortOrder: 2,
    description: "Muharraq is Bahrain's second-largest city with healthcare facilities including Muharraq Maternity Hospital and local clinics.",
  },
  {
    slug: "riffa",
    name: "Riffa",
    emirate: "Southern Governorate",
    country: "bh",
    nameAr: "الرفاع",
    latitude: "26.1300000",
    longitude: "50.5550000",
    sortOrder: 3,
    description: "Riffa is one of Bahrain's largest cities with healthcare services including Bahrain Defence Force Hospital and private medical centers.",
  },
  {
    slug: "isa-town",
    name: "Isa Town",
    emirate: "Southern Governorate",
    country: "bh",
    nameAr: "مدينة عيسى",
    latitude: "26.1736000",
    longitude: "50.5478000",
    sortOrder: 4,
    description: "Isa Town is a planned city in central Bahrain with several healthcare clinics and proximity to major hospital facilities.",
  },
  {
    slug: "sitra",
    name: "Sitra",
    emirate: "Capital Governorate",
    country: "bh",
    nameAr: "سترة",
    latitude: "26.1547000",
    longitude: "50.6244000",
    sortOrder: 5,
    description: "Sitra is an island city east of Manama with local healthcare clinics and easy access to Bahrain's main hospitals.",
  },
  {
    slug: "hamad-town",
    name: "Hamad Town",
    emirate: "Northern Governorate",
    country: "bh",
    nameAr: "مدينة حمد",
    latitude: "26.1167000",
    longitude: "50.4833000",
    sortOrder: 6,
    description: "Hamad Town is Bahrain's largest residential area with healthcare centers and clinics serving its large population.",
  },
  {
    slug: "budaiya",
    name: "Budaiya",
    emirate: "Northern Governorate",
    country: "bh",
    nameAr: "البديع",
    latitude: "26.2189000",
    longitude: "50.4500000",
    sortOrder: 7,
    description: "Budaiya is a western Bahrain suburb with local healthcare facilities and proximity to Manama's major hospitals.",
  },

  // ─── Kuwait Cities ────────────────────────────────────────────────────────────

  {
    slug: "kuwait-city",
    name: "Kuwait City",
    emirate: "Capital Governorate",
    country: "kw",
    nameAr: "مدينة الكويت",
    latitude: "29.3759000",
    longitude: "47.9774000",
    sortOrder: 1,
    description: "Kuwait City is the capital and main healthcare center of Kuwait, home to major government and private hospitals including Mubarak Al Kabeer Hospital.",
  },
  {
    slug: "hawalli",
    name: "Hawalli",
    emirate: "Hawalli Governorate",
    country: "kw",
    nameAr: "حولي",
    latitude: "29.3328000",
    longitude: "48.0286000",
    sortOrder: 2,
    description: "Hawalli is a densely populated area in Kuwait with numerous clinics and private healthcare facilities serving its diverse population.",
  },
  {
    slug: "salmiya",
    name: "Salmiya",
    emirate: "Hawalli Governorate",
    country: "kw",
    nameAr: "السالمية",
    latitude: "29.3347000",
    longitude: "48.0758000",
    sortOrder: 3,
    description: "Salmiya is a major commercial and residential area in Kuwait with a high concentration of private clinics and specialist medical centers.",
  },
  {
    slug: "farwaniya",
    name: "Farwaniya",
    emirate: "Farwaniya Governorate",
    country: "kw",
    nameAr: "الفروانية",
    latitude: "29.2775000",
    longitude: "47.9581000",
    sortOrder: 4,
    description: "Farwaniya is Kuwait's most populated governorate with Farwaniya Hospital and extensive private healthcare infrastructure.",
  },
  {
    slug: "jahra",
    name: "Jahra",
    emirate: "Jahra Governorate",
    country: "kw",
    nameAr: "الجهراء",
    latitude: "29.3375000",
    longitude: "47.6581000",
    sortOrder: 5,
    description: "Jahra is a northwestern Kuwait governorate with healthcare centered around Jahra Hospital and community health centers.",
  },
  {
    slug: "ahmadi",
    name: "Ahmadi",
    emirate: "Ahmadi Governorate",
    country: "kw",
    nameAr: "الأحمدي",
    latitude: "29.0769000",
    longitude: "48.0839000",
    sortOrder: 6,
    description: "Ahmadi is a southern Kuwait city originally built for the oil industry, with Adan Hospital and several private medical facilities.",
  },
  {
    slug: "mangaf",
    name: "Mangaf",
    emirate: "Ahmadi Governorate",
    country: "kw",
    nameAr: "المنقف",
    latitude: "29.0975000",
    longitude: "48.1286000",
    sortOrder: 7,
    description: "Mangaf is a coastal residential area in southern Kuwait with local clinics and proximity to Ahmadi's healthcare facilities.",
  },
] as const;

export const AREAS: Record<string, { slug: string; name: string; nameAr?: string; latitude: string; longitude: string }[]> = {
  dubai: [
    { slug: "jumeirah", name: "Jumeirah", nameAr: "جميرا", latitude: "25.2173", longitude: "55.2529" },
    { slug: "dubai-marina", name: "Dubai Marina", nameAr: "مرسى دبي", latitude: "25.0805", longitude: "55.1403" },
    { slug: "deira", name: "Deira", nameAr: "ديرة", latitude: "25.2717", longitude: "55.3182" },
    { slug: "bur-dubai", name: "Bur Dubai", nameAr: "بر دبي", latitude: "25.2532", longitude: "55.2936" },
    { slug: "al-barsha", name: "Al Barsha", nameAr: "البرشاء", latitude: "25.1134", longitude: "55.2006" },
    { slug: "jlt", name: "JLT (Jumeirah Lake Towers)", nameAr: "أبراج بحيرات جميرا", latitude: "25.0735", longitude: "55.1440" },
    { slug: "downtown-dubai", name: "Downtown Dubai", nameAr: "وسط مدينة دبي", latitude: "25.1972", longitude: "55.2744" },
    { slug: "business-bay", name: "Business Bay", nameAr: "الخليج التجاري", latitude: "25.1851", longitude: "55.2711" },
    { slug: "healthcare-city", name: "Dubai Healthcare City", nameAr: "مدينة دبي الطبية", latitude: "25.2260", longitude: "55.3190" },
    { slug: "al-quoz", name: "Al Quoz", nameAr: "القوز", latitude: "25.1464", longitude: "55.2321" },
    { slug: "silicon-oasis", name: "Dubai Silicon Oasis", nameAr: "واحة دبي للسيليكون", latitude: "25.1199", longitude: "55.3781" },
    { slug: "discovery-gardens", name: "Discovery Gardens", nameAr: "ديسكفري جاردنز", latitude: "25.0381", longitude: "55.1316" },
    { slug: "jvc", name: "JVC (Jumeirah Village Circle)", nameAr: "قرية جميرا الدائرية", latitude: "25.0581", longitude: "55.2133" },
    { slug: "motor-city", name: "Motor City", nameAr: "موتور سيتي", latitude: "25.0482", longitude: "55.2360" },
    { slug: "al-nahda", name: "Al Nahda", nameAr: "النهضة", latitude: "25.2920", longitude: "55.3704" },
    { slug: "international-city", name: "International City", nameAr: "المدينة العالمية", latitude: "25.1651", longitude: "55.4041" },
    { slug: "palm-jumeirah", name: "Palm Jumeirah", nameAr: "نخلة جميرا", latitude: "25.1124", longitude: "55.1390" },
    { slug: "mirdif", name: "Mirdif", nameAr: "مردف", latitude: "25.2169", longitude: "55.4186" },
    { slug: "al-karama", name: "Al Karama", nameAr: "الكرامة", latitude: "25.2417", longitude: "55.3017" },
    { slug: "dubai-hills", name: "Dubai Hills", nameAr: "دبي هيلز", latitude: "25.1207", longitude: "55.2460" },
    { slug: "al-rashidiya", name: "Al Rashidiya", nameAr: "الراشدية", latitude: "25.2359", longitude: "55.3912" },
    { slug: "al-mamzar", name: "Al Mamzar", nameAr: "المنزر", latitude: "25.2960", longitude: "55.3475" },
    { slug: "umm-suqeim", name: "Umm Suqeim", nameAr: "أم سقيم", latitude: "25.1365", longitude: "55.1990" },
    { slug: "al-satwa", name: "Al Satwa", nameAr: "السطوة", latitude: "25.2273", longitude: "55.2656" },
  ],
  "abu-dhabi": [
    { slug: "khalifa-city", name: "Khalifa City", nameAr: "مدينة خليفة", latitude: "24.4200", longitude: "54.5800" },
    { slug: "al-reem-island", name: "Al Reem Island", nameAr: "جزيرة الريم", latitude: "24.4971", longitude: "54.4040" },
    { slug: "al-maryah-island", name: "Al Maryah Island", nameAr: "جزيرة المارية", latitude: "24.5013", longitude: "54.3958" },
    { slug: "corniche", name: "Corniche", nameAr: "الكورنيش", latitude: "24.4764", longitude: "54.3480" },
    { slug: "al-mushrif", name: "Al Mushrif", nameAr: "المشرف", latitude: "24.4572", longitude: "54.3850" },
    { slug: "mohammed-bin-zayed-city", name: "Mohammed Bin Zayed City", nameAr: "مدينة محمد بن زايد", latitude: "24.3531", longitude: "54.5500" },
    { slug: "al-bateen", name: "Al Bateen", nameAr: "البطين", latitude: "24.4618", longitude: "54.3521" },
    { slug: "al-khalidiya", name: "Al Khalidiya", nameAr: "الخالدية", latitude: "24.4721", longitude: "54.3580" },
    { slug: "tourist-club-area", name: "Tourist Club Area", nameAr: "منطقة النادي السياحي", latitude: "24.4898", longitude: "54.3781" },
    { slug: "al-shamkha", name: "Al Shamkha", nameAr: "الشامخة", latitude: "24.3500", longitude: "54.7200" },
    { slug: "saadiyat-island", name: "Saadiyat Island", nameAr: "جزيرة السعديات", latitude: "24.5400", longitude: "54.4300" },
    { slug: "yas-island", name: "Yas Island", nameAr: "جزيرة ياس", latitude: "24.4899", longitude: "54.6025" },
  ],
  sharjah: [
    { slug: "al-nahda-sharjah", name: "Al Nahda", nameAr: "النهضة", latitude: "25.3067", longitude: "55.3764" },
    { slug: "al-majaz", name: "Al Majaz", nameAr: "المجاز", latitude: "25.3399", longitude: "55.3906" },
    { slug: "al-taawun", name: "Al Taawun", nameAr: "التعاون", latitude: "25.3213", longitude: "55.3839" },
    { slug: "al-khan", name: "Al Khan", nameAr: "الخان", latitude: "25.3288", longitude: "55.3669" },
    { slug: "muwaileh", name: "Muwaileh", nameAr: "مويلح", latitude: "25.3033", longitude: "55.4465" },
    { slug: "university-city-sharjah", name: "University City", nameAr: "المدينة الجامعية", latitude: "25.2900", longitude: "55.4600" },
    { slug: "al-qasimia", name: "Al Qasimia", nameAr: "القاسمية", latitude: "25.3515", longitude: "55.3902" },
    { slug: "al-mamzar-sharjah", name: "Al Mamzar", nameAr: "المنزر", latitude: "25.3060", longitude: "55.3560" },
  ],
  ajman: [
    { slug: "al-nuaimia", name: "Al Nuaimia", nameAr: "النعيمية", latitude: "25.3997", longitude: "55.4469" },
    { slug: "al-rashidiya-ajman", name: "Al Rashidiya", nameAr: "الراشدية", latitude: "25.4100", longitude: "55.4670" },
    { slug: "al-jurf", name: "Al Jurf", nameAr: "الجرف", latitude: "25.4120", longitude: "55.5080" },
    { slug: "ajman-downtown", name: "Ajman Downtown", nameAr: "وسط عجمان", latitude: "25.4133", longitude: "55.4408" },
  ],
  "ras-al-khaimah": [
    { slug: "al-nakheel-rak", name: "Al Nakheel", nameAr: "النخيل", latitude: "25.7887", longitude: "55.9548" },
    { slug: "al-hamra-rak", name: "Al Hamra", nameAr: "الحمراء", latitude: "25.6856", longitude: "55.7821" },
    { slug: "khuzam", name: "Khuzam", nameAr: "خزام", latitude: "25.7700", longitude: "55.9550" },
    { slug: "rak-city-center", name: "RAK City Center", nameAr: "وسط رأس الخيمة", latitude: "25.7870", longitude: "55.9600" },
  ],
  fujairah: [
    { slug: "fujairah-city-center", name: "Fujairah City Center", nameAr: "وسط الفجيرة", latitude: "25.1220", longitude: "56.3410" },
    { slug: "dibba-al-fujairah", name: "Dibba Al Fujairah", nameAr: "دبا الفجيرة", latitude: "25.5932", longitude: "56.2614" },
  ],
  "umm-al-quwain": [
    { slug: "uaq-city-center", name: "UAQ City Center", nameAr: "وسط أم القيوين", latitude: "25.5647", longitude: "55.5553" },
    { slug: "al-salamah-uaq", name: "Al Salamah", nameAr: "السلامة", latitude: "25.5500", longitude: "55.5600" },
  ],
  "al-ain": [
    { slug: "al-jimi", name: "Al Jimi", nameAr: "الجيمي", latitude: "24.2186", longitude: "55.7445" },
    { slug: "al-muwaiji", name: "Al Muwaiji", nameAr: "المويجعي", latitude: "24.2100", longitude: "55.7500" },
    { slug: "al-sarooj", name: "Al Sarooj", nameAr: "السروج", latitude: "24.2200", longitude: "55.7600" },
    { slug: "al-ain-central", name: "Al Ain Central", nameAr: "وسط العين", latitude: "24.1917", longitude: "55.7606" },
    { slug: "tawam", name: "Tawam", nameAr: "توام", latitude: "24.2300", longitude: "55.7700" },
    { slug: "al-hili", name: "Al Hili", nameAr: "الهيلي", latitude: "24.2600", longitude: "55.7800" },
  ],
};
