export const CITIES = [
  {
    slug: "dubai",
    name: "Dubai",
    emirate: "Dubai",
    nameAr: "دبي",
    latitude: "25.2048493",
    longitude: "55.2707828",
    sortOrder: 1,
    description: "Dubai is the most populous city in the UAE, home to world-class hospitals, specialty clinics, and healthcare free zones including Dubai Healthcare City (DHCC).",
  },
  {
    slug: "abu-dhabi",
    name: "Abu Dhabi",
    emirate: "Abu Dhabi",
    nameAr: "أبوظبي",
    latitude: "24.4538352",
    longitude: "54.3773438",
    sortOrder: 2,
    description: "Abu Dhabi, the capital of the UAE, offers premier healthcare services regulated by the Department of Health (DOH), with major facilities on Al Reem Island, Al Maryah Island, and Khalifa City.",
  },
  {
    slug: "sharjah",
    name: "Sharjah",
    emirate: "Sharjah",
    nameAr: "الشارقة",
    latitude: "25.3462900",
    longitude: "55.4209000",
    sortOrder: 3,
    description: "Sharjah is the third-largest emirate, with a growing healthcare sector offering affordable clinics and hospitals across Al Nahda, Al Majaz, and Al Taawun.",
  },
  {
    slug: "ajman",
    name: "Ajman",
    emirate: "Ajman",
    nameAr: "عجمان",
    latitude: "25.4052165",
    longitude: "55.5136433",
    sortOrder: 4,
    description: "Ajman offers accessible healthcare services with clinics and hospitals serving the emirate's growing population.",
  },
  {
    slug: "ras-al-khaimah",
    name: "Ras Al Khaimah",
    emirate: "Ras Al Khaimah",
    nameAr: "رأس الخيمة",
    latitude: "25.7895300",
    longitude: "55.9432000",
    sortOrder: 5,
    description: "Ras Al Khaimah features a mix of government and private healthcare facilities, with growing medical tourism especially in wellness and rehabilitation.",
  },
  {
    slug: "fujairah",
    name: "Fujairah",
    emirate: "Fujairah",
    nameAr: "الفجيرة",
    latitude: "25.1288500",
    longitude: "56.3264600",
    sortOrder: 6,
    description: "Fujairah, on the eastern coast of the UAE, provides essential healthcare services through its government hospital and private clinics.",
  },
  {
    slug: "umm-al-quwain",
    name: "Umm Al Quwain",
    emirate: "Umm Al Quwain",
    nameAr: "أم القيوين",
    latitude: "25.5647200",
    longitude: "55.5553200",
    sortOrder: 7,
    description: "Umm Al Quwain is the least populated emirate, with healthcare services centered around the main city area.",
  },
  {
    slug: "al-ain",
    name: "Al Ain",
    emirate: "Abu Dhabi",
    nameAr: "العين",
    latitude: "24.1917200",
    longitude: "55.7606400",
    sortOrder: 8,
    description: "Al Ain, the Garden City of the UAE, is home to Tawam Hospital and several private healthcare facilities serving the inland region.",
  },
] as const;

export const AREAS: Record<string, { slug: string; name: string; nameAr?: string; latitude: string; longitude: string }[]> = {
  dubai: [
    { slug: "jumeirah", name: "Jumeirah", nameAr: "جميرا", latitude: "25.2173", longitude: "55.2529" },
    { slug: "dubai-marina", name: "Dubai Marina", nameAr: "مرسى دبي", latitude: "25.0805", longitude: "55.1403" },
    { slug: "deira", name: "Deira", nameAr: "ديرة", latitude: "25.2717", longitude: "55.3182" },
    { slug: "bur-dubai", name: "Bur Dubai", nameAr: "بر دبي", latitude: "25.2532", longitude: "55.2936" },
    { slug: "al-barsha", name: "Al Barsha", nameAr: "البرشاء", latitude: "25.1134", longitude: "55.2006" },
    { slug: "jlt", name: "JLT (Jumeirah Lake Towers)", nameAr: "أبراج بحيرات جميرا", latitude: "25.0735", longitude: "55.1440" },
    { slug: "downtown-dubai", name: "Downtown Dubai", nameAr: "وسط مدينة دبي", latitude: "25.1972", longitude: "55.2744" },
    { slug: "business-bay", name: "Business Bay", nameAr: "الخليج التجاري", latitude: "25.1851", longitude: "55.2711" },
    { slug: "healthcare-city", name: "Dubai Healthcare City", nameAr: "مدينة دبي الطبية", latitude: "25.2260", longitude: "55.3190" },
    { slug: "al-quoz", name: "Al Quoz", nameAr: "القوز", latitude: "25.1464", longitude: "55.2321" },
    { slug: "silicon-oasis", name: "Dubai Silicon Oasis", nameAr: "واحة دبي للسيليكون", latitude: "25.1199", longitude: "55.3781" },
    { slug: "discovery-gardens", name: "Discovery Gardens", nameAr: "ديسكفري جاردنز", latitude: "25.0381", longitude: "55.1316" },
    { slug: "jvc", name: "JVC (Jumeirah Village Circle)", nameAr: "قرية جميرا الدائرية", latitude: "25.0581", longitude: "55.2133" },
    { slug: "motor-city", name: "Motor City", nameAr: "موتور سيتي", latitude: "25.0482", longitude: "55.2360" },
    { slug: "al-nahda", name: "Al Nahda", nameAr: "النهضة", latitude: "25.2920", longitude: "55.3704" },
    { slug: "international-city", name: "International City", nameAr: "المدينة العالمية", latitude: "25.1651", longitude: "55.4041" },
    { slug: "palm-jumeirah", name: "Palm Jumeirah", nameAr: "نخلة جميرا", latitude: "25.1124", longitude: "55.1390" },
    { slug: "mirdif", name: "Mirdif", nameAr: "مردف", latitude: "25.2169", longitude: "55.4186" },
    { slug: "al-karama", name: "Al Karama", nameAr: "الكرامة", latitude: "25.2417", longitude: "55.3017" },
    { slug: "dubai-hills", name: "Dubai Hills", nameAr: "دبي هيلز", latitude: "25.1207", longitude: "55.2460" },
    { slug: "al-rashidiya", name: "Al Rashidiya", nameAr: "الراشدية", latitude: "25.2359", longitude: "55.3912" },
    { slug: "al-mamzar", name: "Al Mamzar", nameAr: "المنزر", latitude: "25.2960", longitude: "55.3475" },
    { slug: "umm-suqeim", name: "Umm Suqeim", nameAr: "أم سقيم", latitude: "25.1365", longitude: "55.1990" },
    { slug: "al-satwa", name: "Al Satwa", nameAr: "السطوة", latitude: "25.2273", longitude: "55.2656" },
  ],
  "abu-dhabi": [
    { slug: "khalifa-city", name: "Khalifa City", nameAr: "مدينة خليفة", latitude: "24.4200", longitude: "54.5800" },
    { slug: "al-reem-island", name: "Al Reem Island", nameAr: "جزيرة الريم", latitude: "24.4971", longitude: "54.4040" },
    { slug: "al-maryah-island", name: "Al Maryah Island", nameAr: "جزيرة المارية", latitude: "24.5013", longitude: "54.3958" },
    { slug: "corniche", name: "Corniche", nameAr: "الكورنيش", latitude: "24.4764", longitude: "54.3480" },
    { slug: "al-mushrif", name: "Al Mushrif", nameAr: "المشرف", latitude: "24.4572", longitude: "54.3850" },
    { slug: "mohammed-bin-zayed-city", name: "Mohammed Bin Zayed City", nameAr: "مدينة محمد بن زايد", latitude: "24.3531", longitude: "54.5500" },
    { slug: "al-bateen", name: "Al Bateen", nameAr: "البطين", latitude: "24.4618", longitude: "54.3521" },
    { slug: "al-khalidiya", name: "Al Khalidiya", nameAr: "الخالدية", latitude: "24.4721", longitude: "54.3580" },
    { slug: "tourist-club-area", name: "Tourist Club Area", nameAr: "منطقة النادي السياحي", latitude: "24.4898", longitude: "54.3781" },
    { slug: "al-shamkha", name: "Al Shamkha", nameAr: "الشامخة", latitude: "24.3500", longitude: "54.7200" },
    { slug: "saadiyat-island", name: "Saadiyat Island", nameAr: "جزيرة السعديات", latitude: "24.5400", longitude: "54.4300" },
    { slug: "yas-island", name: "Yas Island", nameAr: "جزيرة ياس", latitude: "24.4899", longitude: "54.6025" },
  ],
  sharjah: [
    { slug: "al-nahda-sharjah", name: "Al Nahda", nameAr: "النهضة", latitude: "25.3067", longitude: "55.3764" },
    { slug: "al-majaz", name: "Al Majaz", nameAr: "المجاز", latitude: "25.3399", longitude: "55.3906" },
    { slug: "al-taawun", name: "Al Taawun", nameAr: "التعاون", latitude: "25.3213", longitude: "55.3839" },
    { slug: "al-khan", name: "Al Khan", nameAr: "الخان", latitude: "25.3288", longitude: "55.3669" },
    { slug: "muwaileh", name: "Muwaileh", nameAr: "مويلح", latitude: "25.3033", longitude: "55.4465" },
    { slug: "university-city-sharjah", name: "University City", nameAr: "المدينة الجامعية", latitude: "25.2900", longitude: "55.4600" },
    { slug: "al-qasimia", name: "Al Qasimia", nameAr: "القاسمية", latitude: "25.3515", longitude: "55.3902" },
    { slug: "al-mamzar-sharjah", name: "Al Mamzar", nameAr: "المنزر", latitude: "25.3060", longitude: "55.3560" },
  ],
  ajman: [
    { slug: "al-nuaimia", name: "Al Nuaimia", nameAr: "النعيمية", latitude: "25.3997", longitude: "55.4469" },
    { slug: "al-rashidiya-ajman", name: "Al Rashidiya", nameAr: "الراشدية", latitude: "25.4100", longitude: "55.4670" },
    { slug: "al-jurf", name: "Al Jurf", nameAr: "الجرف", latitude: "25.4120", longitude: "55.5080" },
    { slug: "ajman-downtown", name: "Ajman Downtown", nameAr: "وسط عجمان", latitude: "25.4133", longitude: "55.4408" },
  ],
  "ras-al-khaimah": [
    { slug: "al-nakheel-rak", name: "Al Nakheel", nameAr: "النخيل", latitude: "25.7887", longitude: "55.9548" },
    { slug: "al-hamra-rak", name: "Al Hamra", nameAr: "الحمراء", latitude: "25.6856", longitude: "55.7821" },
    { slug: "khuzam", name: "Khuzam", nameAr: "خزام", latitude: "25.7700", longitude: "55.9550" },
    { slug: "rak-city-center", name: "RAK City Center", nameAr: "وسط رأس الخيمة", latitude: "25.7870", longitude: "55.9600" },
  ],
  fujairah: [
    { slug: "fujairah-city-center", name: "Fujairah City Center", nameAr: "وسط الفجيرة", latitude: "25.1220", longitude: "56.3410" },
    { slug: "dibba-al-fujairah", name: "Dibba Al Fujairah", nameAr: "دبا الفجيرة", latitude: "25.5932", longitude: "56.2614" },
  ],
  "umm-al-quwain": [
    { slug: "uaq-city-center", name: "UAQ City Center", nameAr: "وسط أم القيوين", latitude: "25.5647", longitude: "55.5553" },
    { slug: "al-salamah-uaq", name: "Al Salamah", nameAr: "السلامة", latitude: "25.5500", longitude: "55.5600" },
  ],
  "al-ain": [
    { slug: "al-jimi", name: "Al Jimi", nameAr: "الجيمي", latitude: "24.2186", longitude: "55.7445" },
    { slug: "al-muwaiji", name: "Al Muwaiji", nameAr: "المويجعي", latitude: "24.2100", longitude: "55.7500" },
    { slug: "al-sarooj", name: "Al Sarooj", nameAr: "السروج", latitude: "24.2200", longitude: "55.7600" },
    { slug: "al-ain-central", name: "Al Ain Central", nameAr: "وسط العين", latitude: "24.1917", longitude: "55.7606" },
    { slug: "tawam", name: "Tawam", nameAr: "توام", latitude: "24.2300", longitude: "55.7700" },
    { slug: "al-hili", name: "Al Hili", nameAr: "الهيلي", latitude: "24.2600", longitude: "55.7800" },
  ],
};
