/**
 * UAE Medical Procedure Pricing Data
 *
 * Pricing is derived from:
 * - DOH Abu Dhabi Mandatory Tariff (Shafafiya) — base tariff using RVU × AED conversion
 * - DOH multiplier rules (1x–3x per service category)
 * - DHA Dubai DRG parameters for inpatient procedures
 * - Market-observed ranges from published UAE healthcare cost data (2024–2026)
 *
 * All prices in AED. Ranges reflect variation across government, private, and
 * premium facilities. Individual provider quotes may differ.
 *
 * IMPORTANT: These are indicative ranges for consumer guidance only.
 */

// ─── Types ──────────────────────────────────────────────────────────────────────

export interface CityPricing {
  min: number;
  max: number;
  typical: number;
}

export interface MedicalProcedure {
  slug: string;
  name: string;
  nameAr: string;
  /** Maps to CATEGORIES in categories.ts */
  categorySlug: string;
  /** CPT code for cross-referencing with official tariffs */
  cptCode: string;
  description: string;
  /** What happens during this procedure (patient-facing explanation) */
  whatToExpect: string;
  /** DOH Mandatory Tariff base price in AED (where applicable) */
  baseTariffAed: number;
  /** Observed price range across all UAE facilities */
  priceRange: { min: number; max: number };
  /** City-specific pricing — keyed by city slug */
  cityPricing: Record<string, CityPricing>;
  /** How commonly covered by insurance */
  insuranceCoverage: "typically-covered" | "partially-covered" | "rarely-covered" | "not-covered";
  /** Insurance coverage notes for the patient */
  insuranceNotes: string;
  /** Average procedure duration */
  duration: string;
  /** Recovery time */
  recoveryTime: string;
  /** Whether this is inpatient, outpatient, or either */
  setting: "inpatient" | "outpatient" | "day-case" | "either";
  /** Related procedure slugs */
  relatedProcedures: string[];
  /** Common search terms / aliases for SEO */
  searchTerms: string[];
  /** Whether anaesthesia is typically required */
  anaesthesia: "none" | "local" | "sedation" | "general" | "varies";
  sortOrder: number;
}

export interface ProcedureCategory {
  slug: string;
  name: string;
  description: string;
  icon: string;
  procedureCount?: number;
}

// ─── Procedure Categories (for the pricing hub) ────────────────────────────────

export const PROCEDURE_CATEGORIES: ProcedureCategory[] = [
  { slug: "diagnostics", name: "Diagnostics & Imaging", description: "MRI, CT scan, X-ray, ultrasound, blood tests, and other diagnostic procedures", icon: "ScanLine" },
  { slug: "dental", name: "Dental Procedures", description: "Dental implants, crowns, root canals, braces, teeth whitening, and oral surgery", icon: "Smile" },
  { slug: "eye-care", name: "Eye Care & Vision", description: "LASIK, cataract surgery, retinal treatments, and eye examinations", icon: "Eye" },
  { slug: "surgical", name: "General Surgery", description: "Appendectomy, hernia repair, gallbladder removal, and other surgical procedures", icon: "Scissors" },
  { slug: "orthopedic", name: "Orthopedic Surgery", description: "Knee replacement, hip replacement, ACL repair, and joint procedures", icon: "Bone" },
  { slug: "maternity", name: "Maternity & Childbirth", description: "Normal delivery, C-section, prenatal screening, and fertility treatments", icon: "Baby" },
  { slug: "cosmetic", name: "Cosmetic & Aesthetic", description: "Rhinoplasty, liposuction, hair transplant, Botox, and dermal fillers", icon: "Sparkles" },
  { slug: "cardiac", name: "Cardiac Procedures", description: "Angiography, angioplasty, bypass surgery, and heart valve procedures", icon: "HeartPulse" },
  { slug: "wellness", name: "Consultations & Wellness", description: "GP visits, specialist consultations, health checkups, and preventive care", icon: "Stethoscope" },
  { slug: "therapy", name: "Therapy & Rehabilitation", description: "Physiotherapy, mental health therapy, speech therapy, and rehabilitation", icon: "Activity" },
];

// ─── Procedure Data ─────────────────────────────────────────────────────────────

export const PROCEDURES: MedicalProcedure[] = [
  // ────────────── DIAGNOSTICS & IMAGING ──────────────

  {
    slug: "mri-scan",
    name: "MRI Scan",
    nameAr: "التصوير بالرنين المغناطيسي",
    categorySlug: "radiology-imaging",
    cptCode: "70553",
    description: "Magnetic Resonance Imaging (MRI) uses powerful magnets and radio waves to create detailed images of organs and tissues inside the body. It is commonly used to examine the brain, spine, joints, abdomen, and soft tissues without radiation exposure.",
    whatToExpect: "You will lie on a moveable table that slides into a large tube-shaped scanner. The procedure is painless but can be noisy. You may receive a contrast dye injection for clearer images. The scan takes 30–60 minutes. You must remove all metal objects beforehand.",
    baseTariffAed: 1200,
    priceRange: { min: 800, max: 5000 },
    cityPricing: {
      dubai: { min: 1200, max: 5000, typical: 2500 },
      "abu-dhabi": { min: 1000, max: 4500, typical: 2200 },
      sharjah: { min: 800, max: 3500, typical: 1800 },
      ajman: { min: 800, max: 3000, typical: 1600 },
      "ras-al-khaimah": { min: 900, max: 3200, typical: 1700 },
      fujairah: { min: 900, max: 3000, typical: 1600 },
      "umm-al-quwain": { min: 800, max: 2800, typical: 1500 },
      "al-ain": { min: 900, max: 3500, typical: 1800 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Most insurance plans cover MRI scans when medically necessary and referred by a doctor. Basic plans may require pre-approval. Co-pay of 10–20% applies on most plans. Without insurance, expect to pay the full amount upfront.",
    duration: "30–60 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["ct-scan", "x-ray", "ultrasound"],
    searchTerms: ["MRI scan cost Dubai", "MRI price UAE", "how much does an MRI cost", "magnetic resonance imaging Dubai", "MRI scan near me", "brain MRI cost", "knee MRI cost Dubai", "spine MRI UAE"],
    anaesthesia: "none",
    sortOrder: 1,
  },
  {
    slug: "ct-scan",
    name: "CT Scan",
    nameAr: "الأشعة المقطعية",
    categorySlug: "radiology-imaging",
    cptCode: "74177",
    description: "A CT (Computed Tomography) scan uses X-rays and a computer to create detailed cross-sectional images of the body. It is faster than an MRI and particularly useful for examining bones, blood vessels, and internal organs in the chest, abdomen, and pelvis.",
    whatToExpect: "You will lie on a table that passes through a doughnut-shaped machine. The scan itself takes 10–30 minutes. You may need to drink or be injected with contrast dye. The procedure is painless.",
    baseTariffAed: 800,
    priceRange: { min: 500, max: 4000 },
    cityPricing: {
      dubai: { min: 800, max: 4000, typical: 1800 },
      "abu-dhabi": { min: 700, max: 3500, typical: 1600 },
      sharjah: { min: 500, max: 2800, typical: 1300 },
      ajman: { min: 500, max: 2500, typical: 1200 },
      "ras-al-khaimah": { min: 600, max: 2600, typical: 1300 },
      fujairah: { min: 600, max: 2500, typical: 1200 },
      "umm-al-quwain": { min: 500, max: 2300, typical: 1100 },
      "al-ain": { min: 600, max: 2800, typical: 1400 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "CT scans are covered by most UAE insurance plans when medically indicated. Pre-authorisation may be required for enhanced and basic plans. Expect 10–20% co-pay.",
    duration: "10–30 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["mri-scan", "x-ray", "ultrasound"],
    searchTerms: ["CT scan cost Dubai", "CT scan price UAE", "CAT scan cost", "computed tomography Dubai", "chest CT scan cost", "abdominal CT scan price"],
    anaesthesia: "none",
    sortOrder: 2,
  },
  {
    slug: "x-ray",
    name: "X-Ray",
    nameAr: "الأشعة السينية",
    categorySlug: "radiology-imaging",
    cptCode: "71046",
    description: "An X-ray produces images of structures inside the body using a small dose of ionising radiation. It is the most common and widely available diagnostic imaging technique, used to examine bones, teeth, chest, and abdomen.",
    whatToExpect: "You will stand, sit, or lie down depending on the body part being X-rayed. A technician positions the X-ray machine and you hold still for a few seconds. The entire process takes 5–15 minutes. There is no pain.",
    baseTariffAed: 150,
    priceRange: { min: 80, max: 600 },
    cityPricing: {
      dubai: { min: 100, max: 600, typical: 250 },
      "abu-dhabi": { min: 100, max: 500, typical: 220 },
      sharjah: { min: 80, max: 400, typical: 180 },
      ajman: { min: 80, max: 350, typical: 160 },
      "ras-al-khaimah": { min: 80, max: 400, typical: 170 },
      fujairah: { min: 80, max: 350, typical: 160 },
      "umm-al-quwain": { min: 80, max: 300, typical: 150 },
      "al-ain": { min: 90, max: 400, typical: 180 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "X-rays are almost universally covered by UAE health insurance plans, including basic mandatory schemes. Co-pay is typically 10–20%. No pre-authorisation required in most cases.",
    duration: "5–15 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["ct-scan", "mri-scan", "ultrasound"],
    searchTerms: ["X-ray cost Dubai", "X-ray price UAE", "chest X-ray cost", "bone X-ray price"],
    anaesthesia: "none",
    sortOrder: 3,
  },
  {
    slug: "ultrasound",
    name: "Ultrasound",
    nameAr: "الموجات فوق الصوتية",
    categorySlug: "radiology-imaging",
    cptCode: "76700",
    description: "Ultrasound uses high-frequency sound waves to produce images of structures within the body. It is safe, painless, and does not use radiation. Commonly used for pregnancy monitoring, abdominal scans, thyroid imaging, and musculoskeletal assessment.",
    whatToExpect: "A gel is applied to the skin over the area being examined. A handheld device (transducer) is pressed against the skin and moved around. Images appear in real time on a monitor. The procedure takes 15–45 minutes.",
    baseTariffAed: 400,
    priceRange: { min: 200, max: 1500 },
    cityPricing: {
      dubai: { min: 300, max: 1500, typical: 700 },
      "abu-dhabi": { min: 250, max: 1300, typical: 600 },
      sharjah: { min: 200, max: 1000, typical: 450 },
      ajman: { min: 200, max: 900, typical: 400 },
      "ras-al-khaimah": { min: 200, max: 1000, typical: 450 },
      fujairah: { min: 200, max: 900, typical: 400 },
      "umm-al-quwain": { min: 200, max: 800, typical: 380 },
      "al-ain": { min: 250, max: 1000, typical: 500 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Ultrasound scans are covered by virtually all UAE insurance plans. Pre-authorisation is rarely required for standard diagnostic ultrasounds. Pregnancy-related ultrasounds covered under maternity benefit.",
    duration: "15–45 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["x-ray", "ct-scan", "mri-scan"],
    searchTerms: ["ultrasound cost Dubai", "ultrasound price UAE", "pregnancy scan cost", "abdominal ultrasound price", "sonogram cost Dubai"],
    anaesthesia: "none",
    sortOrder: 4,
  },
  {
    slug: "blood-test",
    name: "Blood Test (CBC + Metabolic Panel)",
    nameAr: "تحليل الدم",
    categorySlug: "labs-diagnostics",
    cptCode: "85025",
    description: "A comprehensive blood test includes a Complete Blood Count (CBC) and Basic Metabolic Panel (BMP). It measures red and white blood cells, haemoglobin, glucose, kidney function, electrolytes, and more. It is the most common diagnostic test ordered by doctors.",
    whatToExpect: "A nurse or phlebotomist draws a small sample of blood from a vein in your arm using a needle. The procedure takes 5–10 minutes. Results are typically available within 24–48 hours. Fasting for 8–12 hours may be required for accurate metabolic panel results.",
    baseTariffAed: 120,
    priceRange: { min: 50, max: 500 },
    cityPricing: {
      dubai: { min: 80, max: 500, typical: 200 },
      "abu-dhabi": { min: 70, max: 450, typical: 180 },
      sharjah: { min: 50, max: 350, typical: 150 },
      ajman: { min: 50, max: 300, typical: 130 },
      "ras-al-khaimah": { min: 60, max: 300, typical: 140 },
      fujairah: { min: 60, max: 300, typical: 130 },
      "umm-al-quwain": { min: 50, max: 250, typical: 120 },
      "al-ain": { min: 60, max: 350, typical: 150 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Blood tests are covered by all UAE insurance plans including the basic Daman scheme. Co-pay of 0–20% depending on plan tier. Some enhanced panels (hormones, tumour markers) may need pre-approval.",
    duration: "5–10 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["vitamin-d-test", "thyroid-test", "health-checkup"],
    searchTerms: ["blood test cost Dubai", "CBC test price UAE", "blood work cost", "lab test price Dubai", "metabolic panel cost"],
    anaesthesia: "none",
    sortOrder: 5,
  },
  {
    slug: "vitamin-d-test",
    name: "Vitamin D Test",
    nameAr: "فحص فيتامين د",
    categorySlug: "labs-diagnostics",
    cptCode: "82306",
    description: "A Vitamin D blood test measures the level of 25-hydroxyvitamin D in your blood. Vitamin D deficiency is extremely common in the UAE despite abundant sunshine, largely because people spend most of their time indoors in air-conditioned environments.",
    whatToExpect: "A simple blood draw from your arm. Results take 24–72 hours. No fasting required. Your doctor will interpret the results and may recommend supplements if levels are below 30 ng/mL.",
    baseTariffAed: 100,
    priceRange: { min: 50, max: 350 },
    cityPricing: {
      dubai: { min: 80, max: 350, typical: 150 },
      "abu-dhabi": { min: 70, max: 300, typical: 130 },
      sharjah: { min: 50, max: 250, typical: 110 },
      ajman: { min: 50, max: 200, typical: 100 },
      "ras-al-khaimah": { min: 60, max: 250, typical: 110 },
      fujairah: { min: 60, max: 200, typical: 100 },
      "umm-al-quwain": { min: 50, max: 200, typical: 90 },
      "al-ain": { min: 60, max: 250, typical: 110 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Most plans cover Vitamin D testing when ordered by a physician. Some basic plans may consider it part of a wellness package requiring a co-pay. Standalone screenings may not be covered.",
    duration: "5 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["blood-test", "thyroid-test", "health-checkup"],
    searchTerms: ["vitamin D test cost Dubai", "vitamin D check price UAE", "25-OH vitamin D test"],
    anaesthesia: "none",
    sortOrder: 6,
  },
  {
    slug: "thyroid-test",
    name: "Thyroid Function Test (TSH + T3/T4)",
    nameAr: "فحص الغدة الدرقية",
    categorySlug: "labs-diagnostics",
    cptCode: "84443",
    description: "A thyroid function test measures TSH (Thyroid Stimulating Hormone), T3, and T4 levels in the blood to assess how well the thyroid gland is working. It is used to diagnose hypothyroidism, hyperthyroidism, and monitor thyroid treatment.",
    whatToExpect: "A simple blood draw from your arm. No special preparation is needed, though morning testing is preferred. Results are available within 24–48 hours.",
    baseTariffAed: 150,
    priceRange: { min: 80, max: 500 },
    cityPricing: {
      dubai: { min: 120, max: 500, typical: 250 },
      "abu-dhabi": { min: 100, max: 450, typical: 220 },
      sharjah: { min: 80, max: 350, typical: 180 },
      ajman: { min: 80, max: 300, typical: 160 },
      "ras-al-khaimah": { min: 90, max: 350, typical: 170 },
      fujairah: { min: 90, max: 300, typical: 160 },
      "umm-al-quwain": { min: 80, max: 280, typical: 150 },
      "al-ain": { min: 100, max: 350, typical: 180 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Thyroid function tests are covered by most UAE insurance plans when ordered by a doctor. Enhanced plans typically cover the full panel (TSH, Free T3, Free T4). Basic plans may only cover TSH.",
    duration: "5 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["blood-test", "vitamin-d-test", "health-checkup"],
    searchTerms: ["thyroid test cost Dubai", "TSH test price UAE", "thyroid function test cost"],
    anaesthesia: "none",
    sortOrder: 7,
  },
  {
    slug: "health-checkup",
    name: "Comprehensive Health Checkup",
    nameAr: "الفحص الطبي الشامل",
    categorySlug: "clinics",
    cptCode: "99395",
    description: "A comprehensive health checkup includes a general physical examination, blood tests (CBC, lipid profile, liver function, kidney function, blood sugar), urine analysis, ECG, chest X-ray, and doctor consultation. Packages vary by provider but typically cover 30+ parameters.",
    whatToExpect: "Arrive fasting (8–12 hours). The checkup takes 2–4 hours and includes blood draws, urine sample, vital signs, vision and hearing tests, and a physical exam. A doctor reviews the results and provides a consultation. Full report available within 48–72 hours.",
    baseTariffAed: 500,
    priceRange: { min: 300, max: 5000 },
    cityPricing: {
      dubai: { min: 500, max: 5000, typical: 1500 },
      "abu-dhabi": { min: 400, max: 4500, typical: 1300 },
      sharjah: { min: 300, max: 3500, typical: 1000 },
      ajman: { min: 300, max: 3000, typical: 900 },
      "ras-al-khaimah": { min: 350, max: 3200, typical: 950 },
      fujairah: { min: 350, max: 3000, typical: 900 },
      "umm-al-quwain": { min: 300, max: 2800, typical: 850 },
      "al-ain": { min: 350, max: 3500, typical: 1000 },
    },
    insuranceCoverage: "partially-covered",
    insuranceNotes: "Preventive health checkups are covered annually by enhanced and premium plans. Basic plans typically do not cover routine checkups. When covered, the scope may be limited to basic screening parameters.",
    duration: "2–4 hours",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["blood-test", "vitamin-d-test", "ecg", "mammogram"],
    searchTerms: ["health checkup cost Dubai", "full body checkup price UAE", "medical checkup Dubai", "annual health screening cost"],
    anaesthesia: "none",
    sortOrder: 8,
  },
  {
    slug: "ecg",
    name: "ECG / EKG (Electrocardiogram)",
    nameAr: "تخطيط القلب الكهربائي",
    categorySlug: "cardiology",
    cptCode: "93000",
    description: "An electrocardiogram (ECG or EKG) records the electrical activity of the heart through electrodes placed on the chest. It detects irregular heart rhythms, heart attacks, enlarged heart chambers, and other cardiac conditions.",
    whatToExpect: "Small sticky patches (electrodes) are placed on your chest, arms, and legs. You lie still for 5–10 minutes while the machine records your heart's electrical activity. The test is painless and non-invasive.",
    baseTariffAed: 100,
    priceRange: { min: 50, max: 400 },
    cityPricing: {
      dubai: { min: 80, max: 400, typical: 180 },
      "abu-dhabi": { min: 70, max: 350, typical: 160 },
      sharjah: { min: 50, max: 300, typical: 130 },
      ajman: { min: 50, max: 250, typical: 120 },
      "ras-al-khaimah": { min: 60, max: 280, typical: 130 },
      fujairah: { min: 60, max: 250, typical: 120 },
      "umm-al-quwain": { min: 50, max: 230, typical: 110 },
      "al-ain": { min: 60, max: 300, typical: 140 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "ECGs are covered by all UAE insurance plans when ordered by a physician. No pre-authorisation needed. Typically zero or minimal co-pay applies.",
    duration: "5–10 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["echocardiogram", "health-checkup", "cardiac-catheterization"],
    searchTerms: ["ECG cost Dubai", "EKG price UAE", "electrocardiogram cost", "heart test Dubai"],
    anaesthesia: "none",
    sortOrder: 9,
  },
  {
    slug: "mammogram",
    name: "Mammogram",
    nameAr: "تصوير الثدي الشعاعي",
    categorySlug: "radiology-imaging",
    cptCode: "77067",
    description: "A mammogram is an X-ray image of the breast used to screen for and detect breast cancer. It is the standard screening tool recommended for women over 40 in the UAE. Digital mammography and 3D tomosynthesis offer higher detection rates.",
    whatToExpect: "Each breast is placed on a flat surface and compressed with a paddle for a few seconds while the X-ray is taken. Two views are typically taken of each breast. The compression can be uncomfortable but lasts only seconds. The entire exam takes 15–20 minutes.",
    baseTariffAed: 350,
    priceRange: { min: 200, max: 1200 },
    cityPricing: {
      dubai: { min: 300, max: 1200, typical: 600 },
      "abu-dhabi": { min: 250, max: 1100, typical: 550 },
      sharjah: { min: 200, max: 900, typical: 450 },
      ajman: { min: 200, max: 800, typical: 400 },
      "ras-al-khaimah": { min: 220, max: 850, typical: 420 },
      fujairah: { min: 220, max: 800, typical: 400 },
      "umm-al-quwain": { min: 200, max: 750, typical: 380 },
      "al-ain": { min: 250, max: 900, typical: 450 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Screening mammograms are covered annually by most enhanced and premium plans for women over 40. Basic plans may cover it as part of preventive care. Diagnostic mammograms (following a finding) are typically fully covered.",
    duration: "15–20 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["ultrasound", "health-checkup"],
    searchTerms: ["mammogram cost Dubai", "breast screening price UAE", "mammography cost", "breast cancer screening Dubai"],
    anaesthesia: "none",
    sortOrder: 10,
  },

  // ────────────── DENTAL ──────────────

  {
    slug: "dental-cleaning",
    name: "Dental Cleaning (Scale & Polish)",
    nameAr: "تنظيف الأسنان",
    categorySlug: "dental",
    cptCode: "D1110",
    description: "Professional dental cleaning removes plaque, tartar (calculus), and stains from teeth. A dental hygienist uses ultrasonic instruments and hand tools to clean above and below the gumline. It is recommended every 6 months to prevent gum disease and cavities.",
    whatToExpect: "The hygienist uses a scaler to remove tartar, polishes teeth with a gritty paste, and flosses. The procedure is mostly painless. You may experience sensitivity during cleaning if there is significant tartar buildup.",
    baseTariffAed: 200,
    priceRange: { min: 150, max: 800 },
    cityPricing: {
      dubai: { min: 200, max: 800, typical: 400 },
      "abu-dhabi": { min: 180, max: 700, typical: 350 },
      sharjah: { min: 150, max: 600, typical: 280 },
      ajman: { min: 150, max: 500, typical: 250 },
      "ras-al-khaimah": { min: 150, max: 550, typical: 270 },
      fujairah: { min: 150, max: 500, typical: 250 },
      "umm-al-quwain": { min: 150, max: 450, typical: 230 },
      "al-ain": { min: 160, max: 600, typical: 280 },
    },
    insuranceCoverage: "partially-covered",
    insuranceNotes: "Dental cleaning is covered under plans with dental benefits, typically 1–2 times per year. Basic and many enhanced plans do not include dental. When covered, annual dental sub-limits of AED 2,000–10,000 apply.",
    duration: "30–60 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["dental-crown", "root-canal", "dental-implant", "teeth-whitening"],
    searchTerms: ["dental cleaning cost Dubai", "teeth cleaning price UAE", "scale and polish cost", "dental hygienist cost Dubai"],
    anaesthesia: "none",
    sortOrder: 11,
  },
  {
    slug: "dental-crown",
    name: "Dental Crown",
    nameAr: "تاج الأسنان",
    categorySlug: "dental",
    cptCode: "D2740",
    description: "A dental crown is a cap placed over a damaged or decayed tooth to restore its shape, size, and strength. Crowns are made from porcelain, ceramic, metal alloy, or zirconia. They typically last 10–15 years with proper care.",
    whatToExpect: "The tooth is filed down to make room for the crown. An impression is taken and sent to a lab. A temporary crown is placed. You return in 1–2 weeks for the permanent crown to be cemented. Same-day crowns using CAD/CAM technology are available at some clinics.",
    baseTariffAed: 1000,
    priceRange: { min: 600, max: 4000 },
    cityPricing: {
      dubai: { min: 1000, max: 4000, typical: 2000 },
      "abu-dhabi": { min: 900, max: 3500, typical: 1800 },
      sharjah: { min: 600, max: 2800, typical: 1400 },
      ajman: { min: 600, max: 2500, typical: 1200 },
      "ras-al-khaimah": { min: 700, max: 2600, typical: 1300 },
      fujairah: { min: 700, max: 2500, typical: 1200 },
      "umm-al-quwain": { min: 600, max: 2300, typical: 1100 },
      "al-ain": { min: 700, max: 2800, typical: 1400 },
    },
    insuranceCoverage: "partially-covered",
    insuranceNotes: "Dental crowns are covered under plans with dental benefits and may require pre-authorisation. Coverage is usually partial (50–80%) up to the annual dental sub-limit. Cosmetic-only crowns are not covered.",
    duration: "1–2 hours (per visit, 2 visits)",
    recoveryTime: "1–2 days mild sensitivity",
    setting: "outpatient",
    relatedProcedures: ["root-canal", "dental-implant", "dental-cleaning"],
    searchTerms: ["dental crown cost Dubai", "tooth cap price UAE", "porcelain crown cost", "zirconia crown price Dubai"],
    anaesthesia: "local",
    sortOrder: 12,
  },
  {
    slug: "root-canal",
    name: "Root Canal Treatment",
    nameAr: "علاج قناة الجذر",
    categorySlug: "dental",
    cptCode: "D3330",
    description: "Root canal treatment removes infected or inflamed pulp from inside a tooth, cleans and shapes the root canals, and fills them to prevent reinfection. It saves a tooth that would otherwise need extraction. The procedure has a success rate of over 95%.",
    whatToExpect: "Under local anaesthesia, the dentist drills into the tooth to access the pulp chamber. Infected tissue is removed, the canals are cleaned and shaped, then filled with gutta-percha. A crown is usually recommended afterward. The procedure takes 1–2 visits of 60–90 minutes each.",
    baseTariffAed: 1200,
    priceRange: { min: 700, max: 4500 },
    cityPricing: {
      dubai: { min: 1200, max: 4500, typical: 2500 },
      "abu-dhabi": { min: 1000, max: 4000, typical: 2200 },
      sharjah: { min: 700, max: 3200, typical: 1600 },
      ajman: { min: 700, max: 2800, typical: 1400 },
      "ras-al-khaimah": { min: 800, max: 3000, typical: 1500 },
      fujairah: { min: 800, max: 2800, typical: 1400 },
      "umm-al-quwain": { min: 700, max: 2600, typical: 1300 },
      "al-ain": { min: 800, max: 3200, typical: 1600 },
    },
    insuranceCoverage: "partially-covered",
    insuranceNotes: "Root canal treatment is covered by plans with dental benefits when medically necessary. Pre-authorisation is usually required. Coverage is typically 60–80% up to the annual dental sub-limit. Crown after root canal may have a separate claim.",
    duration: "60–90 minutes per visit (1–2 visits)",
    recoveryTime: "2–3 days",
    setting: "outpatient",
    relatedProcedures: ["dental-crown", "dental-implant", "tooth-extraction"],
    searchTerms: ["root canal cost Dubai", "root canal treatment price UAE", "endodontic treatment cost", "root canal near me"],
    anaesthesia: "local",
    sortOrder: 13,
  },
  {
    slug: "dental-implant",
    name: "Dental Implant (Single Tooth)",
    nameAr: "زراعة الأسنان",
    categorySlug: "dental",
    cptCode: "D6010",
    description: "A dental implant replaces a missing tooth with a titanium post surgically placed in the jawbone, topped with an abutment and crown. It looks and functions like a natural tooth. The total process takes 3–6 months as the implant needs time to fuse with the bone (osseointegration).",
    whatToExpect: "Phase 1: The titanium post is surgically placed in the jawbone under local anaesthesia. Phase 2: After 3–6 months of healing, an abutment is attached. Phase 3: A custom crown is placed on the abutment. Prices typically include the implant, abutment, and crown.",
    baseTariffAed: 5000,
    priceRange: { min: 3000, max: 15000 },
    cityPricing: {
      dubai: { min: 5000, max: 15000, typical: 8000 },
      "abu-dhabi": { min: 4500, max: 13000, typical: 7000 },
      sharjah: { min: 3000, max: 10000, typical: 5500 },
      ajman: { min: 3000, max: 9000, typical: 5000 },
      "ras-al-khaimah": { min: 3500, max: 9500, typical: 5500 },
      fujairah: { min: 3500, max: 9000, typical: 5000 },
      "umm-al-quwain": { min: 3000, max: 8500, typical: 4800 },
      "al-ain": { min: 3500, max: 10000, typical: 5500 },
    },
    insuranceCoverage: "rarely-covered",
    insuranceNotes: "Dental implants are rarely covered by UAE insurance plans. Most plans exclude implants entirely or classify them as cosmetic. Premium plans with extensive dental benefits may cover a portion (up to AED 5,000–10,000 dental sub-limit). Self-pay is the norm.",
    duration: "1–2 hours (surgical phase)",
    recoveryTime: "3–6 months (full osseointegration)",
    setting: "outpatient",
    relatedProcedures: ["dental-crown", "tooth-extraction", "root-canal"],
    searchTerms: ["dental implant cost Dubai", "tooth implant price UAE", "implant dentist cost", "dental implant near me", "how much is a dental implant Dubai"],
    anaesthesia: "local",
    sortOrder: 14,
  },
  {
    slug: "teeth-whitening",
    name: "Teeth Whitening (In-Office)",
    nameAr: "تبييض الأسنان",
    categorySlug: "dental",
    cptCode: "D9972",
    description: "In-office teeth whitening uses professional-grade bleaching agents (hydrogen peroxide or carbamide peroxide) activated by UV or LED light to whiten teeth by several shades in a single session. Results are immediate and typically last 6–12 months.",
    whatToExpect: "Your gums are protected with a barrier. A bleaching gel is applied to the teeth and activated with a special light. The process is repeated 2–3 times in one session. You may experience temporary tooth sensitivity for 24–48 hours afterward.",
    baseTariffAed: 800,
    priceRange: { min: 500, max: 3000 },
    cityPricing: {
      dubai: { min: 800, max: 3000, typical: 1500 },
      "abu-dhabi": { min: 700, max: 2800, typical: 1400 },
      sharjah: { min: 500, max: 2200, typical: 1100 },
      ajman: { min: 500, max: 2000, typical: 1000 },
      "ras-al-khaimah": { min: 600, max: 2200, typical: 1100 },
      fujairah: { min: 600, max: 2000, typical: 1000 },
      "umm-al-quwain": { min: 500, max: 1800, typical: 900 },
      "al-ain": { min: 600, max: 2200, typical: 1100 },
    },
    insuranceCoverage: "not-covered",
    insuranceNotes: "Teeth whitening is classified as a cosmetic procedure and is not covered by any UAE health insurance plan. Full self-pay applies.",
    duration: "60–90 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["dental-cleaning", "dental-crown", "dental-veneer"],
    searchTerms: ["teeth whitening cost Dubai", "tooth whitening price UAE", "Zoom whitening cost", "laser teeth whitening Dubai"],
    anaesthesia: "none",
    sortOrder: 15,
  },
  {
    slug: "dental-veneer",
    name: "Dental Veneers (Porcelain, per tooth)",
    nameAr: "قشور الأسنان",
    categorySlug: "dental",
    cptCode: "D2962",
    description: "Dental veneers are thin porcelain or composite shells bonded to the front surface of teeth to improve appearance. They correct discolouration, chips, gaps, and minor misalignment. Porcelain veneers last 10–20 years.",
    whatToExpect: "A thin layer of enamel is removed from the front of the tooth. An impression is taken and sent to a lab. Temporary veneers may be placed. You return in 1–2 weeks for the permanent veneers to be bonded. The process requires 2–3 visits.",
    baseTariffAed: 1500,
    priceRange: { min: 800, max: 5000 },
    cityPricing: {
      dubai: { min: 1500, max: 5000, typical: 2800 },
      "abu-dhabi": { min: 1300, max: 4500, typical: 2500 },
      sharjah: { min: 800, max: 3500, typical: 1800 },
      ajman: { min: 800, max: 3000, typical: 1600 },
      "ras-al-khaimah": { min: 900, max: 3200, typical: 1700 },
      fujairah: { min: 900, max: 3000, typical: 1600 },
      "umm-al-quwain": { min: 800, max: 2800, typical: 1500 },
      "al-ain": { min: 900, max: 3500, typical: 1800 },
    },
    insuranceCoverage: "not-covered",
    insuranceNotes: "Dental veneers are classified as cosmetic and not covered by UAE insurance plans. Full self-pay applies.",
    duration: "1–2 hours per visit (2–3 visits)",
    recoveryTime: "1–2 days sensitivity",
    setting: "outpatient",
    relatedProcedures: ["dental-crown", "teeth-whitening", "dental-cleaning"],
    searchTerms: ["veneer cost Dubai", "dental veneer price UAE", "porcelain veneer cost", "Lumineers cost Dubai", "Hollywood smile cost"],
    anaesthesia: "local",
    sortOrder: 16,
  },
  {
    slug: "tooth-extraction",
    name: "Tooth Extraction",
    nameAr: "خلع الأسنان",
    categorySlug: "dental",
    cptCode: "D7140",
    description: "Tooth extraction is the removal of a tooth from its socket in the jawbone. Simple extractions involve loosening the tooth with an elevator and removing it with forceps. Surgical extractions are needed for impacted or broken teeth.",
    whatToExpect: "Under local anaesthesia, the dentist loosens the tooth and removes it. You bite on gauze for 30–45 minutes to control bleeding. Mild discomfort and swelling are normal for 2–3 days. Wisdom tooth extraction may involve minor surgery.",
    baseTariffAed: 300,
    priceRange: { min: 150, max: 2500 },
    cityPricing: {
      dubai: { min: 300, max: 2500, typical: 800 },
      "abu-dhabi": { min: 250, max: 2200, typical: 700 },
      sharjah: { min: 150, max: 1800, typical: 550 },
      ajman: { min: 150, max: 1600, typical: 500 },
      "ras-al-khaimah": { min: 200, max: 1700, typical: 550 },
      fujairah: { min: 200, max: 1600, typical: 500 },
      "umm-al-quwain": { min: 150, max: 1500, typical: 480 },
      "al-ain": { min: 200, max: 1800, typical: 550 },
    },
    insuranceCoverage: "partially-covered",
    insuranceNotes: "Simple extractions are covered by plans with dental benefits. Surgical extractions (wisdom teeth) may require pre-authorisation. Coverage is typically 70–100% within the dental sub-limit.",
    duration: "20–60 minutes",
    recoveryTime: "2–5 days",
    setting: "outpatient",
    relatedProcedures: ["dental-implant", "root-canal", "dental-crown"],
    searchTerms: ["tooth extraction cost Dubai", "wisdom tooth removal price UAE", "tooth pulling cost", "dental extraction near me"],
    anaesthesia: "local",
    sortOrder: 17,
  },

  // ────────────── EYE CARE ──────────────

  {
    slug: "lasik",
    name: "LASIK Eye Surgery",
    nameAr: "عملية الليزك",
    categorySlug: "ophthalmology",
    cptCode: "65760",
    description: "LASIK (Laser-Assisted In Situ Keratomileusis) reshapes the cornea using an excimer laser to correct myopia (nearsightedness), hyperopia (farsightedness), and astigmatism. It reduces or eliminates the need for glasses or contact lenses. Success rates exceed 96%.",
    whatToExpect: "Eye-numbing drops are applied. A thin flap is created on the cornea using a femtosecond laser. The excimer laser reshapes the cornea underneath. The flap is repositioned. The procedure takes 10–15 minutes per eye. Most patients achieve 20/20 vision within 24 hours.",
    baseTariffAed: 4000,
    priceRange: { min: 3000, max: 12000 },
    cityPricing: {
      dubai: { min: 4000, max: 12000, typical: 7000 },
      "abu-dhabi": { min: 3500, max: 11000, typical: 6500 },
      sharjah: { min: 3000, max: 9000, typical: 5000 },
      ajman: { min: 3000, max: 8500, typical: 4800 },
      "ras-al-khaimah": { min: 3500, max: 9000, typical: 5200 },
      fujairah: { min: 3500, max: 8500, typical: 5000 },
      "umm-al-quwain": { min: 3000, max: 8000, typical: 4500 },
      "al-ain": { min: 3500, max: 9000, typical: 5500 },
    },
    insuranceCoverage: "rarely-covered",
    insuranceNotes: "LASIK is typically classified as elective/cosmetic and excluded from most UAE insurance plans. Some premium corporate plans may offer partial coverage or a fixed allowance (AED 5,000–10,000). Check your specific plan.",
    duration: "10–15 minutes per eye",
    recoveryTime: "1–3 days (most activities), 1 month (full stabilisation)",
    setting: "day-case",
    relatedProcedures: ["cataract-surgery"],
    searchTerms: ["LASIK cost Dubai", "LASIK eye surgery price UAE", "laser eye surgery cost", "LASIK near me", "how much is LASIK in Dubai"],
    anaesthesia: "local",
    sortOrder: 18,
  },
  {
    slug: "cataract-surgery",
    name: "Cataract Surgery",
    nameAr: "عملية المياه البيضاء",
    categorySlug: "ophthalmology",
    cptCode: "66984",
    description: "Cataract surgery removes the clouded natural lens of the eye and replaces it with an artificial intraocular lens (IOL). It is one of the most commonly performed surgeries in the world, with a very high success rate. Phacoemulsification is the standard technique.",
    whatToExpect: "The eye is numbed with drops. A tiny incision is made, and ultrasound energy breaks up the cloudy lens. The fragments are suctioned out and a new IOL is inserted. The incision self-seals. Each eye is done separately, usually 1–2 weeks apart. Surgery takes 15–30 minutes.",
    baseTariffAed: 5000,
    priceRange: { min: 3000, max: 20000 },
    cityPricing: {
      dubai: { min: 5000, max: 20000, typical: 10000 },
      "abu-dhabi": { min: 4500, max: 18000, typical: 9000 },
      sharjah: { min: 3000, max: 14000, typical: 7000 },
      ajman: { min: 3000, max: 12000, typical: 6500 },
      "ras-al-khaimah": { min: 3500, max: 13000, typical: 7000 },
      fujairah: { min: 3500, max: 12000, typical: 6500 },
      "umm-al-quwain": { min: 3000, max: 11000, typical: 6000 },
      "al-ain": { min: 3500, max: 14000, typical: 7500 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Cataract surgery is medically necessary and covered by most UAE insurance plans including Daman basic. Pre-authorisation is required. Standard monofocal IOLs are covered; premium multifocal or toric IOLs may incur an out-of-pocket upgrade fee of AED 3,000–8,000.",
    duration: "15–30 minutes per eye",
    recoveryTime: "1–2 weeks (most activities), 4–6 weeks (full)",
    setting: "day-case",
    relatedProcedures: ["lasik"],
    searchTerms: ["cataract surgery cost Dubai", "cataract operation price UAE", "lens replacement cost", "IOL surgery price"],
    anaesthesia: "local",
    sortOrder: 19,
  },

  // ────────────── GENERAL SURGERY ──────────────

  {
    slug: "endoscopy",
    name: "Endoscopy (Upper GI)",
    nameAr: "المنظار العلوي",
    categorySlug: "gastroenterology",
    cptCode: "43239",
    description: "Upper GI endoscopy (esophagogastroduodenoscopy or EGD) examines the esophagus, stomach, and upper part of the small intestine using a flexible tube with a camera. It diagnoses ulcers, GERD, Barrett's esophagus, celiac disease, and detects early cancers.",
    whatToExpect: "You fast for 6–8 hours before the procedure. Light sedation is given through an IV. A thin flexible scope is passed through the mouth into the stomach. The doctor examines the lining and may take biopsies. The procedure takes 15–30 minutes. You rest for 1–2 hours after sedation wears off.",
    baseTariffAed: 2000,
    priceRange: { min: 1000, max: 6000 },
    cityPricing: {
      dubai: { min: 1500, max: 6000, typical: 3500 },
      "abu-dhabi": { min: 1300, max: 5500, typical: 3000 },
      sharjah: { min: 1000, max: 4500, typical: 2500 },
      ajman: { min: 1000, max: 4000, typical: 2200 },
      "ras-al-khaimah": { min: 1200, max: 4200, typical: 2400 },
      fujairah: { min: 1200, max: 4000, typical: 2200 },
      "umm-al-quwain": { min: 1000, max: 3800, typical: 2100 },
      "al-ain": { min: 1200, max: 4500, typical: 2500 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Diagnostic endoscopy is covered when medically indicated with a doctor's referral. Pre-authorisation is required by most plans. Co-pay of 10–20% applies. Biopsies and pathology are billed separately.",
    duration: "15–30 minutes",
    recoveryTime: "1–2 hours (post-sedation), full day rest recommended",
    setting: "day-case",
    relatedProcedures: ["colonoscopy"],
    searchTerms: ["endoscopy cost Dubai", "gastroscopy price UAE", "stomach scope cost", "upper GI endoscopy price"],
    anaesthesia: "sedation",
    sortOrder: 20,
  },
  {
    slug: "colonoscopy",
    name: "Colonoscopy",
    nameAr: "تنظير القولون",
    categorySlug: "gastroenterology",
    cptCode: "45378",
    description: "A colonoscopy examines the large intestine (colon) and rectum using a flexible tube with a camera. It is the gold standard for colorectal cancer screening and detects polyps, inflammation, and other abnormalities. Polyps can be removed during the procedure.",
    whatToExpect: "You undergo bowel preparation the day before (drinking a laxative solution). Light sedation is given. The scope is inserted through the rectum and advanced through the colon. The procedure takes 30–60 minutes. You rest for 1–2 hours post-sedation.",
    baseTariffAed: 2500,
    priceRange: { min: 1500, max: 8000 },
    cityPricing: {
      dubai: { min: 2000, max: 8000, typical: 4500 },
      "abu-dhabi": { min: 1800, max: 7000, typical: 4000 },
      sharjah: { min: 1500, max: 5500, typical: 3200 },
      ajman: { min: 1500, max: 5000, typical: 2800 },
      "ras-al-khaimah": { min: 1600, max: 5200, typical: 3000 },
      fujairah: { min: 1600, max: 5000, typical: 2800 },
      "umm-al-quwain": { min: 1500, max: 4800, typical: 2700 },
      "al-ain": { min: 1600, max: 5500, typical: 3200 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Colonoscopy is covered by most plans when medically necessary or as screening for patients over 45. Pre-authorisation required. Polyp removal during the procedure is usually covered. Co-pay of 10–20% applies.",
    duration: "30–60 minutes",
    recoveryTime: "1–2 hours (post-sedation), full day rest recommended",
    setting: "day-case",
    relatedProcedures: ["endoscopy"],
    searchTerms: ["colonoscopy cost Dubai", "colonoscopy price UAE", "colon cancer screening cost", "bowel screening price"],
    anaesthesia: "sedation",
    sortOrder: 21,
  },
  {
    slug: "appendectomy",
    name: "Appendectomy (Laparoscopic)",
    nameAr: "استئصال الزائدة الدودية",
    categorySlug: "hospitals",
    cptCode: "44970",
    description: "Laparoscopic appendectomy is the surgical removal of the appendix through 2–3 small incisions using a camera and specialised instruments. It is the standard treatment for appendicitis. Laparoscopic surgery offers faster recovery and less scarring than open surgery.",
    whatToExpect: "Under general anaesthesia, 2–3 small incisions (5–12mm) are made in the abdomen. Carbon dioxide inflates the abdomen for visibility. A camera and instruments are inserted to remove the appendix. Surgery takes 30–60 minutes. Hospital stay is typically 1–2 days.",
    baseTariffAed: 15000,
    priceRange: { min: 10000, max: 40000 },
    cityPricing: {
      dubai: { min: 15000, max: 40000, typical: 25000 },
      "abu-dhabi": { min: 13000, max: 35000, typical: 22000 },
      sharjah: { min: 10000, max: 30000, typical: 18000 },
      ajman: { min: 10000, max: 28000, typical: 16000 },
      "ras-al-khaimah": { min: 11000, max: 28000, typical: 17000 },
      fujairah: { min: 11000, max: 27000, typical: 16000 },
      "umm-al-quwain": { min: 10000, max: 26000, typical: 15000 },
      "al-ain": { min: 12000, max: 30000, typical: 18000 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Appendectomy is an emergency/medically necessary procedure and is fully covered by all UAE insurance plans including basic schemes. Hospital admission, surgeon fee, anaesthesia, and post-operative care are included. Co-pay on the inpatient component is typically 0–10%.",
    duration: "30–60 minutes",
    recoveryTime: "1–3 weeks",
    setting: "inpatient",
    relatedProcedures: ["hernia-repair"],
    searchTerms: ["appendectomy cost Dubai", "appendix removal price UAE", "appendicitis surgery cost", "laparoscopic appendectomy price"],
    anaesthesia: "general",
    sortOrder: 22,
  },
  {
    slug: "hernia-repair",
    name: "Hernia Repair (Inguinal, Laparoscopic)",
    nameAr: "إصلاح الفتق",
    categorySlug: "hospitals",
    cptCode: "49650",
    description: "Laparoscopic inguinal hernia repair uses mesh to reinforce the weakened area of the abdominal wall where tissue or intestine protrudes. It is one of the most common surgeries performed worldwide. Laparoscopic repair allows faster recovery than open surgery.",
    whatToExpect: "Under general anaesthesia, 3 small incisions are made. A camera and instruments are inserted. Mesh is placed over the hernia defect to reinforce the abdominal wall. Surgery takes 45–90 minutes. Most patients go home the same day or stay one night.",
    baseTariffAed: 15000,
    priceRange: { min: 10000, max: 40000 },
    cityPricing: {
      dubai: { min: 15000, max: 40000, typical: 25000 },
      "abu-dhabi": { min: 13000, max: 35000, typical: 22000 },
      sharjah: { min: 10000, max: 30000, typical: 18000 },
      ajman: { min: 10000, max: 28000, typical: 16000 },
      "ras-al-khaimah": { min: 11000, max: 28000, typical: 17000 },
      fujairah: { min: 11000, max: 27000, typical: 16000 },
      "umm-al-quwain": { min: 10000, max: 26000, typical: 15000 },
      "al-ain": { min: 12000, max: 30000, typical: 18000 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Hernia repair is covered as medically necessary surgery. Pre-authorisation required. Inpatient co-pay of 0–10% applies depending on plan. Day-case or one-night stay is typical.",
    duration: "45–90 minutes",
    recoveryTime: "1–2 weeks (light activity), 4–6 weeks (full)",
    setting: "either",
    relatedProcedures: ["appendectomy"],
    searchTerms: ["hernia repair cost Dubai", "inguinal hernia surgery price UAE", "hernia operation cost", "laparoscopic hernia repair price"],
    anaesthesia: "general",
    sortOrder: 23,
  },

  // ────────────── ORTHOPEDIC ──────────────

  {
    slug: "knee-replacement",
    name: "Knee Replacement (Total)",
    nameAr: "استبدال الركبة",
    categorySlug: "orthopedics",
    cptCode: "27447",
    description: "Total knee replacement (arthroplasty) replaces the damaged surfaces of the knee joint with metal and plastic components. It is recommended for severe osteoarthritis, rheumatoid arthritis, or post-traumatic arthritis that has not responded to conservative treatment.",
    whatToExpect: "Under general or spinal anaesthesia, the surgeon removes damaged cartilage and bone from the knee and implants an artificial joint. Surgery takes 1–2 hours. Hospital stay is 3–5 days. Physiotherapy begins within 24 hours of surgery.",
    baseTariffAed: 40000,
    priceRange: { min: 30000, max: 100000 },
    cityPricing: {
      dubai: { min: 40000, max: 100000, typical: 65000 },
      "abu-dhabi": { min: 35000, max: 90000, typical: 60000 },
      sharjah: { min: 30000, max: 75000, typical: 50000 },
      ajman: { min: 30000, max: 70000, typical: 45000 },
      "ras-al-khaimah": { min: 32000, max: 72000, typical: 48000 },
      fujairah: { min: 32000, max: 70000, typical: 46000 },
      "umm-al-quwain": { min: 30000, max: 68000, typical: 44000 },
      "al-ain": { min: 33000, max: 75000, typical: 50000 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Total knee replacement is covered by most enhanced and premium plans when medically necessary. Pre-authorisation required. Basic plans may have annual limits that do not fully cover the procedure. Implant type may affect coverage — standard implants are typically covered; premium implants may incur an upgrade fee.",
    duration: "1–2 hours",
    recoveryTime: "6–12 weeks (walking), 3–6 months (full recovery)",
    setting: "inpatient",
    relatedProcedures: ["hip-replacement", "acl-reconstruction"],
    searchTerms: ["knee replacement cost Dubai", "total knee arthroplasty price UAE", "knee surgery cost", "joint replacement Dubai"],
    anaesthesia: "general",
    sortOrder: 24,
  },
  {
    slug: "hip-replacement",
    name: "Hip Replacement (Total)",
    nameAr: "استبدال مفصل الورك",
    categorySlug: "orthopedics",
    cptCode: "27130",
    description: "Total hip replacement replaces the damaged hip joint with an artificial joint made of metal, ceramic, or plastic. It relieves chronic hip pain and improves mobility for patients with severe arthritis or hip fractures.",
    whatToExpect: "Under general or spinal anaesthesia, the surgeon removes the damaged femoral head and acetabulum and implants the artificial joint. Surgery takes 1–2 hours. Hospital stay is 3–5 days. Physiotherapy begins the day after surgery.",
    baseTariffAed: 45000,
    priceRange: { min: 35000, max: 120000 },
    cityPricing: {
      dubai: { min: 45000, max: 120000, typical: 75000 },
      "abu-dhabi": { min: 40000, max: 110000, typical: 70000 },
      sharjah: { min: 35000, max: 90000, typical: 55000 },
      ajman: { min: 35000, max: 85000, typical: 52000 },
      "ras-al-khaimah": { min: 37000, max: 88000, typical: 54000 },
      fujairah: { min: 37000, max: 85000, typical: 52000 },
      "umm-al-quwain": { min: 35000, max: 82000, typical: 50000 },
      "al-ain": { min: 38000, max: 90000, typical: 58000 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Covered by enhanced and premium plans when medically necessary. Pre-authorisation required. Annual limits may apply. Ceramic-on-ceramic implants may incur additional cost over the standard covered option.",
    duration: "1–2 hours",
    recoveryTime: "6–12 weeks (walking), 3–6 months (full recovery)",
    setting: "inpatient",
    relatedProcedures: ["knee-replacement", "acl-reconstruction"],
    searchTerms: ["hip replacement cost Dubai", "hip arthroplasty price UAE", "hip surgery cost", "joint replacement Dubai"],
    anaesthesia: "general",
    sortOrder: 25,
  },
  {
    slug: "acl-reconstruction",
    name: "ACL Reconstruction",
    nameAr: "إعادة بناء الرباط الصليبي الأمامي",
    categorySlug: "orthopedics",
    cptCode: "29888",
    description: "ACL reconstruction replaces a torn anterior cruciate ligament using a graft (from the patient's own tissue or a donor). It is the standard treatment for active individuals who have torn their ACL, typically during sports.",
    whatToExpect: "Arthroscopic surgery under general anaesthesia. Small incisions around the knee. A graft (usually from the patellar tendon or hamstring) replaces the torn ACL. Surgery takes 1–2 hours. Most patients go home the same day or stay one night. Rehabilitation takes 6–9 months.",
    baseTariffAed: 25000,
    priceRange: { min: 18000, max: 65000 },
    cityPricing: {
      dubai: { min: 25000, max: 65000, typical: 40000 },
      "abu-dhabi": { min: 22000, max: 60000, typical: 37000 },
      sharjah: { min: 18000, max: 50000, typical: 30000 },
      ajman: { min: 18000, max: 45000, typical: 28000 },
      "ras-al-khaimah": { min: 20000, max: 48000, typical: 30000 },
      fujairah: { min: 20000, max: 45000, typical: 28000 },
      "umm-al-quwain": { min: 18000, max: 43000, typical: 27000 },
      "al-ain": { min: 20000, max: 50000, typical: 32000 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "ACL reconstruction is covered as medically necessary surgery by most enhanced and premium plans. Pre-authorisation required. Post-operative physiotherapy is usually covered separately within plan limits.",
    duration: "1–2 hours",
    recoveryTime: "6–9 months (return to sport)",
    setting: "either",
    relatedProcedures: ["knee-replacement", "hip-replacement"],
    searchTerms: ["ACL surgery cost Dubai", "ACL reconstruction price UAE", "knee ligament surgery cost", "ACL repair price"],
    anaesthesia: "general",
    sortOrder: 26,
  },

  // ────────────── MATERNITY ──────────────

  {
    slug: "normal-delivery",
    name: "Normal Delivery (Vaginal Birth)",
    nameAr: "الولادة الطبيعية",
    categorySlug: "ob-gyn",
    cptCode: "59400",
    description: "A normal vaginal delivery is the birth of a baby through the birth canal without surgical intervention. It includes prenatal monitoring, labour and delivery, and post-delivery care. The cost typically covers the obstetrician, midwife, delivery room, and a standard hospital stay of 1–2 days.",
    whatToExpect: "When labour begins, you are admitted to the hospital. Contractions are monitored. An epidural may be offered for pain relief (often billed separately). After delivery, mother and baby stay 1–2 days for observation. The total package typically includes prenatal visits in the final weeks.",
    baseTariffAed: 10000,
    priceRange: { min: 7000, max: 30000 },
    cityPricing: {
      dubai: { min: 10000, max: 30000, typical: 18000 },
      "abu-dhabi": { min: 9000, max: 28000, typical: 16000 },
      sharjah: { min: 7000, max: 22000, typical: 13000 },
      ajman: { min: 7000, max: 20000, typical: 12000 },
      "ras-al-khaimah": { min: 8000, max: 22000, typical: 13000 },
      fujairah: { min: 8000, max: 20000, typical: 12000 },
      "umm-al-quwain": { min: 7000, max: 18000, typical: 11000 },
      "al-ain": { min: 8000, max: 22000, typical: 13000 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Maternity is covered by most enhanced and premium plans after a waiting period (typically 9–12 months). Basic plans exclude maternity. When covered, there may be a sub-limit of AED 10,000–30,000. Pre-natal visits and delivery are usually bundled.",
    duration: "6–18 hours (labour)",
    recoveryTime: "1–2 days (hospital), 4–6 weeks (full)",
    setting: "inpatient",
    relatedProcedures: ["c-section", "ivf"],
    searchTerms: ["normal delivery cost Dubai", "vaginal birth price UAE", "childbirth cost", "delivery hospital charges Dubai", "maternity package cost"],
    anaesthesia: "varies",
    sortOrder: 27,
  },
  {
    slug: "c-section",
    name: "Caesarean Section (C-Section)",
    nameAr: "العملية القيصرية",
    categorySlug: "ob-gyn",
    cptCode: "59510",
    description: "A Caesarean section is the surgical delivery of a baby through an incision in the mother's abdomen and uterus. It may be planned (elective) or emergency. The UAE has one of the higher C-section rates globally. The cost includes surgeon fee, anaesthesia, operating room, and 2–4 day hospital stay.",
    whatToExpect: "Under spinal or general anaesthesia, a horizontal incision is made in the lower abdomen. The baby is delivered within 5–10 minutes. The uterus and abdomen are closed. Hospital stay is typically 2–4 days. Recovery takes 4–8 weeks.",
    baseTariffAed: 18000,
    priceRange: { min: 12000, max: 50000 },
    cityPricing: {
      dubai: { min: 18000, max: 50000, typical: 30000 },
      "abu-dhabi": { min: 16000, max: 45000, typical: 27000 },
      sharjah: { min: 12000, max: 35000, typical: 22000 },
      ajman: { min: 12000, max: 32000, typical: 20000 },
      "ras-al-khaimah": { min: 13000, max: 33000, typical: 21000 },
      fujairah: { min: 13000, max: 32000, typical: 20000 },
      "umm-al-quwain": { min: 12000, max: 30000, typical: 19000 },
      "al-ain": { min: 14000, max: 35000, typical: 22000 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "C-sections are covered under maternity benefits (same waiting period as normal delivery). Emergency C-sections are covered even by plans without maternity benefit. Sub-limits of AED 15,000–40,000 may apply. Private room upgrade may be additional.",
    duration: "45–90 minutes",
    recoveryTime: "2–4 days (hospital), 6–8 weeks (full)",
    setting: "inpatient",
    relatedProcedures: ["normal-delivery", "ivf"],
    searchTerms: ["C-section cost Dubai", "caesarean section price UAE", "C-section delivery charges", "planned C-section cost Dubai"],
    anaesthesia: "general",
    sortOrder: 28,
  },
  {
    slug: "ivf",
    name: "IVF Treatment (One Cycle)",
    nameAr: "أطفال الأنابيب",
    categorySlug: "fertility-ivf",
    cptCode: "58970",
    description: "In Vitro Fertilisation (IVF) involves stimulating the ovaries to produce multiple eggs, retrieving the eggs, fertilising them with sperm in a laboratory, and transferring the resulting embryo(s) into the uterus. One cycle typically takes 4–6 weeks. Success rates in UAE clinics average 35–45% per cycle for women under 35.",
    whatToExpect: "Ovarian stimulation with daily hormone injections for 10–14 days. Egg retrieval under sedation (15–30 minutes). Sperm and eggs are combined in the lab. Embryos develop for 3–5 days. One or two embryos are transferred to the uterus. A pregnancy test follows 10–14 days later. Price typically includes medications, monitoring, retrieval, lab, and transfer.",
    baseTariffAed: 20000,
    priceRange: { min: 15000, max: 50000 },
    cityPricing: {
      dubai: { min: 20000, max: 50000, typical: 30000 },
      "abu-dhabi": { min: 18000, max: 45000, typical: 28000 },
      sharjah: { min: 15000, max: 38000, typical: 24000 },
      ajman: { min: 15000, max: 35000, typical: 22000 },
      "ras-al-khaimah": { min: 16000, max: 36000, typical: 23000 },
      fujairah: { min: 16000, max: 35000, typical: 22000 },
      "umm-al-quwain": { min: 15000, max: 33000, typical: 21000 },
      "al-ain": { min: 17000, max: 38000, typical: 25000 },
    },
    insuranceCoverage: "rarely-covered",
    insuranceNotes: "IVF is excluded from most UAE insurance plans. Some premium employer-sponsored plans may cover 1–2 cycles with pre-authorisation. The Abu Dhabi government provides IVF support for UAE nationals through specific programmes. Self-pay is the norm for expats.",
    duration: "4–6 weeks per cycle",
    recoveryTime: "1–2 days (after retrieval)",
    setting: "outpatient",
    relatedProcedures: ["normal-delivery", "c-section"],
    searchTerms: ["IVF cost Dubai", "IVF price UAE", "fertility treatment cost", "test tube baby cost Dubai", "IVF clinic price", "in vitro fertilization cost UAE"],
    anaesthesia: "sedation",
    sortOrder: 29,
  },

  // ────────────── COSMETIC ──────────────

  {
    slug: "rhinoplasty",
    name: "Rhinoplasty (Nose Job)",
    nameAr: "تجميل الأنف",
    categorySlug: "cosmetic-plastic",
    cptCode: "30420",
    description: "Rhinoplasty reshapes the nose for cosmetic or functional reasons. It can reduce or increase nose size, change the shape of the tip or bridge, narrow nostrils, or correct breathing problems. It is one of the most popular cosmetic surgeries in the UAE.",
    whatToExpect: "Under general anaesthesia, the surgeon makes incisions inside the nostrils (closed) or across the columella (open). Bone and cartilage are reshaped. A splint is placed on the nose. Surgery takes 1–3 hours. Swelling peaks at 48 hours and gradually resolves over 6–12 months.",
    baseTariffAed: 15000,
    priceRange: { min: 10000, max: 45000 },
    cityPricing: {
      dubai: { min: 15000, max: 45000, typical: 25000 },
      "abu-dhabi": { min: 13000, max: 40000, typical: 23000 },
      sharjah: { min: 10000, max: 32000, typical: 18000 },
      ajman: { min: 10000, max: 30000, typical: 17000 },
      "ras-al-khaimah": { min: 11000, max: 32000, typical: 18000 },
      fujairah: { min: 11000, max: 30000, typical: 17000 },
      "umm-al-quwain": { min: 10000, max: 28000, typical: 16000 },
      "al-ain": { min: 12000, max: 32000, typical: 19000 },
    },
    insuranceCoverage: "not-covered",
    insuranceNotes: "Cosmetic rhinoplasty is not covered by UAE insurance. Functional rhinoplasty (to correct breathing issues like a deviated septum) may be partially covered with medical documentation and pre-authorisation. The cosmetic component remains self-pay.",
    duration: "1–3 hours",
    recoveryTime: "1–2 weeks (return to work), 6–12 months (final result)",
    setting: "either",
    relatedProcedures: ["liposuction", "hair-transplant", "botox"],
    searchTerms: ["rhinoplasty cost Dubai", "nose job price UAE", "nose surgery cost", "nose reshaping Dubai"],
    anaesthesia: "general",
    sortOrder: 30,
  },
  {
    slug: "liposuction",
    name: "Liposuction",
    nameAr: "شفط الدهون",
    categorySlug: "cosmetic-plastic",
    cptCode: "15877",
    description: "Liposuction removes excess fat deposits from specific body areas (abdomen, thighs, arms, chin, back) using suction. Modern techniques include tumescent, VASER (ultrasound-assisted), and laser-assisted liposuction. It contours the body but is not a weight loss procedure.",
    whatToExpect: "Under general or local anaesthesia with sedation, small incisions are made near the treatment area. A cannula (thin tube) is inserted to break up and suction out fat. Surgery takes 1–3 hours depending on areas treated. Compression garments are worn for 4–6 weeks.",
    baseTariffAed: 12000,
    priceRange: { min: 8000, max: 40000 },
    cityPricing: {
      dubai: { min: 12000, max: 40000, typical: 22000 },
      "abu-dhabi": { min: 10000, max: 35000, typical: 20000 },
      sharjah: { min: 8000, max: 28000, typical: 16000 },
      ajman: { min: 8000, max: 26000, typical: 15000 },
      "ras-al-khaimah": { min: 9000, max: 27000, typical: 16000 },
      fujairah: { min: 9000, max: 26000, typical: 15000 },
      "umm-al-quwain": { min: 8000, max: 24000, typical: 14000 },
      "al-ain": { min: 9000, max: 28000, typical: 17000 },
    },
    insuranceCoverage: "not-covered",
    insuranceNotes: "Liposuction is cosmetic and not covered by any UAE insurance plan. Full self-pay applies. Some clinics offer financing or payment plans.",
    duration: "1–3 hours",
    recoveryTime: "1–2 weeks (return to work), 3–6 months (final result)",
    setting: "either",
    relatedProcedures: ["rhinoplasty", "hair-transplant"],
    searchTerms: ["liposuction cost Dubai", "lipo price UAE", "VASER liposuction cost", "fat removal surgery price"],
    anaesthesia: "general",
    sortOrder: 31,
  },
  {
    slug: "hair-transplant",
    name: "Hair Transplant (FUE)",
    nameAr: "زراعة الشعر",
    categorySlug: "dermatology",
    cptCode: "15775",
    description: "FUE (Follicular Unit Extraction) hair transplant involves extracting individual hair follicles from a donor area (usually the back of the head) and implanting them in thinning or bald areas. The procedure creates natural-looking results. A typical session transplants 2,000–4,000 grafts.",
    whatToExpect: "Under local anaesthesia, individual follicular units are extracted one by one from the donor area using a micro-punch tool. Recipient sites are created and grafts are placed. The procedure takes 4–8 hours for a full session. No visible scarring. Transplanted hair sheds initially and regrows permanently over 6–12 months.",
    baseTariffAed: 10000,
    priceRange: { min: 7000, max: 35000 },
    cityPricing: {
      dubai: { min: 10000, max: 35000, typical: 18000 },
      "abu-dhabi": { min: 9000, max: 30000, typical: 16000 },
      sharjah: { min: 7000, max: 25000, typical: 13000 },
      ajman: { min: 7000, max: 22000, typical: 12000 },
      "ras-al-khaimah": { min: 8000, max: 24000, typical: 13000 },
      fujairah: { min: 8000, max: 22000, typical: 12000 },
      "umm-al-quwain": { min: 7000, max: 20000, typical: 11000 },
      "al-ain": { min: 8000, max: 25000, typical: 14000 },
    },
    insuranceCoverage: "not-covered",
    insuranceNotes: "Hair transplant is cosmetic and not covered by UAE insurance plans. Full self-pay applies. Many clinics offer package pricing based on graft count.",
    duration: "4–8 hours",
    recoveryTime: "1–2 weeks (return to work), 6–12 months (final result)",
    setting: "outpatient",
    relatedProcedures: ["rhinoplasty", "botox"],
    searchTerms: ["hair transplant cost Dubai", "FUE hair transplant price UAE", "hair restoration cost", "hair implant Dubai", "hair transplant per graft cost"],
    anaesthesia: "local",
    sortOrder: 32,
  },
  {
    slug: "botox",
    name: "Botox Injections",
    nameAr: "حقن البوتوكس",
    categorySlug: "dermatology",
    cptCode: "64612",
    description: "Botox (botulinum toxin type A) injections temporarily relax facial muscles to smooth wrinkles and fine lines. Common treatment areas include forehead lines, crow's feet, frown lines (glabella), and bunny lines. Results last 3–6 months. It is also used medically for migraines, excessive sweating, and jaw clenching.",
    whatToExpect: "A thin needle injects small amounts of Botox into targeted muscles. The procedure takes 10–20 minutes with minimal discomfort. No downtime is needed. Results appear within 3–7 days and peak at 2 weeks. Follow-up treatments every 3–6 months maintain results.",
    baseTariffAed: 800,
    priceRange: { min: 500, max: 3000 },
    cityPricing: {
      dubai: { min: 800, max: 3000, typical: 1500 },
      "abu-dhabi": { min: 700, max: 2800, typical: 1400 },
      sharjah: { min: 500, max: 2200, typical: 1100 },
      ajman: { min: 500, max: 2000, typical: 1000 },
      "ras-al-khaimah": { min: 600, max: 2200, typical: 1100 },
      fujairah: { min: 600, max: 2000, typical: 1000 },
      "umm-al-quwain": { min: 500, max: 1800, typical: 900 },
      "al-ain": { min: 600, max: 2200, typical: 1100 },
    },
    insuranceCoverage: "not-covered",
    insuranceNotes: "Cosmetic Botox is not covered. Medical Botox for chronic migraines, hyperhidrosis, or TMJ may be partially covered by enhanced plans with a neurologist's referral and pre-authorisation.",
    duration: "10–20 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["dermal-fillers", "rhinoplasty", "hair-transplant"],
    searchTerms: ["Botox cost Dubai", "Botox price UAE", "anti-wrinkle injections cost", "Botox per unit price Dubai"],
    anaesthesia: "none",
    sortOrder: 33,
  },
  {
    slug: "dermal-fillers",
    name: "Dermal Fillers",
    nameAr: "حقن الفيلر",
    categorySlug: "dermatology",
    cptCode: "11950",
    description: "Dermal fillers are injectable gels (hyaluronic acid, calcium hydroxylapatite, or poly-L-lactic acid) used to restore volume, smooth wrinkles, enhance lips, and contour facial features. Common areas include lips, cheeks, nasolabial folds, and jawline. Results are immediate and last 6–18 months.",
    whatToExpect: "After applying numbing cream, the practitioner injects filler using a fine needle or cannula. The procedure takes 15–45 minutes depending on the areas treated. Mild swelling and bruising may occur for 2–5 days. Results are visible immediately.",
    baseTariffAed: 1500,
    priceRange: { min: 800, max: 5000 },
    cityPricing: {
      dubai: { min: 1500, max: 5000, typical: 2500 },
      "abu-dhabi": { min: 1300, max: 4500, typical: 2300 },
      sharjah: { min: 800, max: 3500, typical: 1800 },
      ajman: { min: 800, max: 3200, typical: 1600 },
      "ras-al-khaimah": { min: 900, max: 3500, typical: 1800 },
      fujairah: { min: 900, max: 3200, typical: 1600 },
      "umm-al-quwain": { min: 800, max: 3000, typical: 1500 },
      "al-ain": { min: 1000, max: 3500, typical: 1800 },
    },
    insuranceCoverage: "not-covered",
    insuranceNotes: "Dermal fillers are cosmetic and not covered by UAE insurance plans. Full self-pay applies. Price is typically per syringe (1ml).",
    duration: "15–45 minutes",
    recoveryTime: "1–3 days (minimal)",
    setting: "outpatient",
    relatedProcedures: ["botox", "rhinoplasty"],
    searchTerms: ["dermal filler cost Dubai", "filler price UAE", "lip filler cost", "cheek filler price Dubai", "Juvederm cost"],
    anaesthesia: "local",
    sortOrder: 34,
  },

  // ────────────── CARDIAC ──────────────

  {
    slug: "echocardiogram",
    name: "Echocardiogram",
    nameAr: "تخطيط صدى القلب",
    categorySlug: "cardiology",
    cptCode: "93306",
    description: "An echocardiogram uses ultrasound to produce detailed images of the heart's structure and function. It shows heart chambers, valves, blood flow, and pumping strength. It is a key tool for diagnosing heart valve disease, heart failure, and congenital heart defects.",
    whatToExpect: "You lie on your left side. A sonographer applies gel to your chest and moves a transducer to capture images. The test takes 30–60 minutes and is painless. A cardiologist reviews the images and provides a report.",
    baseTariffAed: 500,
    priceRange: { min: 300, max: 2000 },
    cityPricing: {
      dubai: { min: 500, max: 2000, typical: 1000 },
      "abu-dhabi": { min: 400, max: 1800, typical: 900 },
      sharjah: { min: 300, max: 1500, typical: 700 },
      ajman: { min: 300, max: 1300, typical: 650 },
      "ras-al-khaimah": { min: 350, max: 1400, typical: 700 },
      fujairah: { min: 350, max: 1300, typical: 650 },
      "umm-al-quwain": { min: 300, max: 1200, typical: 600 },
      "al-ain": { min: 350, max: 1500, typical: 750 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Echocardiograms are covered by most UAE insurance plans when ordered by a cardiologist or physician. Pre-authorisation may be needed for some plans. Co-pay of 10–20% applies.",
    duration: "30–60 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["ecg", "cardiac-catheterization"],
    searchTerms: ["echocardiogram cost Dubai", "heart ultrasound price UAE", "echo test cost", "cardiac ultrasound price"],
    anaesthesia: "none",
    sortOrder: 35,
  },
  {
    slug: "cardiac-catheterization",
    name: "Cardiac Catheterisation (Angiography)",
    nameAr: "قسطرة القلب",
    categorySlug: "cardiology",
    cptCode: "93458",
    description: "Cardiac catheterisation involves threading a thin catheter through a blood vessel (usually in the wrist or groin) to the heart. Contrast dye is injected and X-ray images show the coronary arteries. It diagnoses blockages and can guide interventions like angioplasty and stenting.",
    whatToExpect: "Under local anaesthesia and sedation, a catheter is inserted through the radial (wrist) or femoral (groin) artery. Contrast dye is injected and X-ray images are taken. If blockages are found, angioplasty may be performed during the same procedure. The diagnostic procedure takes 30–60 minutes. Hospital stay is typically 1 day.",
    baseTariffAed: 10000,
    priceRange: { min: 7000, max: 35000 },
    cityPricing: {
      dubai: { min: 10000, max: 35000, typical: 20000 },
      "abu-dhabi": { min: 9000, max: 32000, typical: 18000 },
      sharjah: { min: 7000, max: 25000, typical: 15000 },
      ajman: { min: 7000, max: 23000, typical: 14000 },
      "ras-al-khaimah": { min: 8000, max: 24000, typical: 15000 },
      fujairah: { min: 8000, max: 23000, typical: 14000 },
      "umm-al-quwain": { min: 7000, max: 22000, typical: 13000 },
      "al-ain": { min: 8000, max: 25000, typical: 16000 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Diagnostic cardiac catheterisation is covered by most UAE insurance plans including basic schemes when medically necessary. Pre-authorisation required. If angioplasty/stenting is performed, additional costs apply and are usually covered. Cardiac stents may have coverage limits.",
    duration: "30–60 minutes (diagnostic)",
    recoveryTime: "1–2 days",
    setting: "inpatient",
    relatedProcedures: ["echocardiogram", "ecg"],
    searchTerms: ["cardiac catheterization cost Dubai", "angiography price UAE", "heart catheter cost", "coronary angiogram price"],
    anaesthesia: "sedation",
    sortOrder: 36,
  },

  // ────────────── CONSULTATIONS & WELLNESS ──────────────

  {
    slug: "gp-consultation",
    name: "GP Consultation",
    nameAr: "استشارة طبيب عام",
    categorySlug: "clinics",
    cptCode: "99213",
    description: "A general practitioner (GP) consultation is a visit to a primary care doctor for general health concerns, routine checkups, sick visits, prescription refills, and referrals to specialists. GPs are the first point of contact in the UAE healthcare system.",
    whatToExpect: "You discuss your health concern with the doctor. A physical examination is performed as needed. The doctor may order tests, prescribe medication, or refer you to a specialist. A typical consultation lasts 15–30 minutes.",
    baseTariffAed: 150,
    priceRange: { min: 100, max: 500 },
    cityPricing: {
      dubai: { min: 150, max: 500, typical: 250 },
      "abu-dhabi": { min: 120, max: 450, typical: 220 },
      sharjah: { min: 100, max: 350, typical: 180 },
      ajman: { min: 100, max: 300, typical: 160 },
      "ras-al-khaimah": { min: 100, max: 350, typical: 170 },
      fujairah: { min: 100, max: 300, typical: 160 },
      "umm-al-quwain": { min: 100, max: 280, typical: 150 },
      "al-ain": { min: 110, max: 350, typical: 180 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "GP consultations are covered by all UAE insurance plans including the basic Daman scheme. Co-pay of 0–20% applies. No referral or pre-authorisation needed. Some plans have a per-visit co-pay of AED 20–50.",
    duration: "15–30 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["specialist-consultation", "health-checkup", "blood-test"],
    searchTerms: ["GP consultation cost Dubai", "doctor visit price UAE", "general practitioner fee", "walk-in clinic cost Dubai"],
    anaesthesia: "none",
    sortOrder: 37,
  },
  {
    slug: "specialist-consultation",
    name: "Specialist Consultation",
    nameAr: "استشارة طبيب أخصائي",
    categorySlug: "clinics",
    cptCode: "99244",
    description: "A specialist consultation is a visit to a medical specialist (cardiologist, dermatologist, orthopedic surgeon, etc.) for expert evaluation of a specific health condition. It may include a physical exam, review of test results, diagnosis, and treatment planning.",
    whatToExpect: "You discuss your condition and medical history with the specialist. A focused examination is performed. The specialist may review previous test results, order additional tests, or recommend treatment. Consultations typically last 20–45 minutes.",
    baseTariffAed: 300,
    priceRange: { min: 200, max: 1200 },
    cityPricing: {
      dubai: { min: 300, max: 1200, typical: 550 },
      "abu-dhabi": { min: 250, max: 1000, typical: 500 },
      sharjah: { min: 200, max: 800, typical: 400 },
      ajman: { min: 200, max: 700, typical: 350 },
      "ras-al-khaimah": { min: 200, max: 750, typical: 380 },
      fujairah: { min: 200, max: 700, typical: 350 },
      "umm-al-quwain": { min: 200, max: 650, typical: 330 },
      "al-ain": { min: 220, max: 800, typical: 400 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Specialist consultations are covered by most UAE insurance plans. Some basic plans may require a GP referral first. Co-pay of 10–20% applies. Follow-up visits are covered the same way.",
    duration: "20–45 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["gp-consultation", "health-checkup"],
    searchTerms: ["specialist doctor cost Dubai", "consultant fee UAE", "cardiologist consultation cost", "dermatologist visit price Dubai"],
    anaesthesia: "none",
    sortOrder: 38,
  },

  // ────────────── THERAPY ──────────────

  {
    slug: "physiotherapy-session",
    name: "Physiotherapy Session",
    nameAr: "جلسة علاج طبيعي",
    categorySlug: "physiotherapy",
    cptCode: "97110",
    description: "A physiotherapy session involves assessment and treatment of musculoskeletal conditions, injuries, and post-surgical rehabilitation. Treatment may include manual therapy, exercise prescription, electrotherapy, dry needling, and movement training.",
    whatToExpect: "The physiotherapist assesses your condition, designs a treatment plan, and provides hands-on treatment. Sessions include exercises, manual therapy, and may use equipment like ultrasound or electrical stimulation. Each session lasts 45–60 minutes. Multiple sessions are usually needed.",
    baseTariffAed: 250,
    priceRange: { min: 150, max: 800 },
    cityPricing: {
      dubai: { min: 250, max: 800, typical: 450 },
      "abu-dhabi": { min: 200, max: 700, typical: 400 },
      sharjah: { min: 150, max: 600, typical: 300 },
      ajman: { min: 150, max: 500, typical: 280 },
      "ras-al-khaimah": { min: 180, max: 550, typical: 300 },
      fujairah: { min: 180, max: 500, typical: 280 },
      "umm-al-quwain": { min: 150, max: 480, typical: 260 },
      "al-ain": { min: 180, max: 600, typical: 320 },
    },
    insuranceCoverage: "typically-covered",
    insuranceNotes: "Physiotherapy is covered by most UAE plans when prescribed by a doctor. Typically limited to 10–20 sessions per year. Pre-authorisation may be needed after the initial sessions. Co-pay of 10–20% applies.",
    duration: "45–60 minutes",
    recoveryTime: "No recovery needed per session",
    setting: "outpatient",
    relatedProcedures: ["acl-reconstruction", "knee-replacement"],
    searchTerms: ["physiotherapy cost Dubai", "physio session price UAE", "physical therapy cost", "rehabilitation therapy price Dubai"],
    anaesthesia: "none",
    sortOrder: 39,
  },
  {
    slug: "psychology-session",
    name: "Psychology / Therapy Session",
    nameAr: "جلسة علاج نفسي",
    categorySlug: "mental-health",
    cptCode: "90834",
    description: "A psychotherapy session provides treatment for mental health conditions including anxiety, depression, trauma, relationship issues, and stress. Common approaches include Cognitive Behavioural Therapy (CBT), EMDR, and psychodynamic therapy. Sessions are conducted by licensed clinical psychologists or counsellors.",
    whatToExpect: "You meet with a therapist in a private, confidential setting. Sessions involve talking about your thoughts, feelings, and behaviours. The therapist may teach coping strategies, assign homework, or guide you through exercises. Sessions typically last 45–60 minutes.",
    baseTariffAed: 500,
    priceRange: { min: 300, max: 1500 },
    cityPricing: {
      dubai: { min: 500, max: 1500, typical: 800 },
      "abu-dhabi": { min: 450, max: 1300, typical: 700 },
      sharjah: { min: 300, max: 1000, typical: 550 },
      ajman: { min: 300, max: 900, typical: 500 },
      "ras-al-khaimah": { min: 350, max: 1000, typical: 550 },
      fujairah: { min: 350, max: 900, typical: 500 },
      "umm-al-quwain": { min: 300, max: 850, typical: 480 },
      "al-ain": { min: 350, max: 1000, typical: 580 },
    },
    insuranceCoverage: "partially-covered",
    insuranceNotes: "Mental health coverage is mandatory under newer UAE insurance regulations. Enhanced and premium plans typically cover 10–20 sessions per year. Basic plans may offer limited sessions. Pre-authorisation is usually required after initial assessment.",
    duration: "45–60 minutes",
    recoveryTime: "No recovery needed",
    setting: "outpatient",
    relatedProcedures: ["gp-consultation", "specialist-consultation"],
    searchTerms: ["psychologist cost Dubai", "therapy session price UAE", "counselling cost", "CBT therapy price Dubai", "mental health therapy cost"],
    anaesthesia: "none",
    sortOrder: 40,
  },
];

// ─── Utility Functions ──────────────────────────────────────────────────────────

export function getProcedureBySlug(slug: string): MedicalProcedure | undefined {
  return PROCEDURES.find((p) => p.slug === slug);
}

export function getProceduresByCategory(procCategory: string): MedicalProcedure[] {
  // Map procedure category slugs to directory category slugs
  const categoryMap: Record<string, string[]> = {
    diagnostics: ["radiology-imaging", "labs-diagnostics"],
    dental: ["dental"],
    "eye-care": ["ophthalmology"],
    surgical: ["hospitals", "gastroenterology"],
    orthopedic: ["orthopedics"],
    maternity: ["ob-gyn", "fertility-ivf"],
    cosmetic: ["cosmetic-plastic", "dermatology"],
    cardiac: ["cardiology"],
    wellness: ["clinics"],
    therapy: ["physiotherapy", "mental-health"],
  };

  const directorySlugs = categoryMap[procCategory] || [];
  return PROCEDURES.filter((p) => directorySlugs.includes(p.categorySlug)).sort(
    (a, b) => a.sortOrder - b.sortOrder
  );
}

export function getAllProcedureSlugs(): string[] {
  return PROCEDURES.map((p) => p.slug);
}

export function searchProcedures(query: string): MedicalProcedure[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];

  return PROCEDURES.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.nameAr.includes(q) ||
      p.searchTerms.some((t) => t.toLowerCase().includes(q)) ||
      p.description.toLowerCase().includes(q) ||
      p.cptCode.includes(q)
  ).sort((a, b) => {
    // Exact name match first
    const aExact = a.name.toLowerCase().startsWith(q) ? 0 : 1;
    const bExact = b.name.toLowerCase().startsWith(q) ? 0 : 1;
    if (aExact !== bExact) return aExact - bExact;
    return a.sortOrder - b.sortOrder;
  });
}

export function formatAed(amount: number): string {
  return `AED ${amount.toLocaleString()}`;
}

export function getProcedureCategoryBySlug(slug: string): ProcedureCategory | undefined {
  return PROCEDURE_CATEGORIES.find((c) => c.slug === slug);
}
